### ISSUE TITLE
Addition of Firebase SDK [GSoC'20][Milestone 1] 

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1095]
Setting up Firebase in the application by - 
- Registering the app on Firebase console.
- Adding the Firebase Configuration file `google-services.json` to our codebase.
- Adding basic Firebase dependencies in both project-level and app-level `build.gradle`. 
- Adding `Crashlytics` dependency and setting it up from console as well
- Enabling `Google Analytics` for our application in the Firebase console and adding its dependency in the codebase.

Important Links - 
- [Add Firebase to your Android project](https://firebase.google.com/docs/android/setup)
- [Setting up Crashlytics](https://firebase.google.com/docs/crashlytics/get-started?platform=android)
- [Setting up Analytics](https://firebase.google.com/docs/crashlytics/get-started?platform=android)

**Comment by aggarwalpulkit596** [comment]
@Sarthak2601 @rt4914 @vinitamurthi as we're implementing this I have a few suggestions 

- Crashlytics and Analytics shouldn't be reported for debug builds - even for the team, we can do that by keeping a separate applicationId suffix for debug build so that there is no mapping on firebase for that project.

- A demo google-services.json for debugging build

**Comment by Sarthak2601** [comment]
All done.
