### ISSUE TITLE
Starting training session uses the wrong skills

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1345]
**Describe the bug**
Additional/different skills seem to be included when starting a training session.

**To Reproduce**
1. Start a training session for the fractions topic by selecting 1 skill
2. Navigate back to the topic, deselect the skill, select a new skill, and start another training session
3. Observe the some of the same questions show up in both; this works for any skill that's selected since there seem to be some base common skills always included

**Expected behavior**
The skills you select should directly correspond to the questions you get in the question player.

**Device**
- On latest ``develop``
- Device: Pixel XL
- SDK: 29

**Comment by BenHenning** [comment]
I'm actually wondering if the current implementation is correct, but the dummy data isn't. It seems like we are selecting subtopics, and we automatically include all of the skills associated with those subtopics. Do we maybe have the subtopics configured weirdly for the lessons included with the app?

@rt4914 can you provide any additional context here?

**Comment by rt4914** [comment]
@BenHenning I think this is working correctly based on the json data we have.
https://github.com/oppia/oppia-android/blob/830a567f85b26b841f5e4e5a868c378c074bb700/domain/src/main/assets/fractions_topic.json#L19

If we check this json file, the three ids `B39yK4cbHZYI  (10 times out of 11)`, `UxTGIJqaHMLa  (9 times out of 11)` and `5RM9KPfQxobH  (7 times out of 11)` are common among almost all subtopics and therefore I think this confusion is because of that.
