### ISSUE TITLE
Landscape support of StatePlayerRecyclerViewAssembler

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1347]
Currently the interactions and button in `StatePlayerRecyclerViewAssembler` do not have full support for landscape mode. If learner types any answer in any input interaction, after configuration change that answer is lost. Also the enable/disable state of `Submit` button is not preserved.

**Comment by BenHenning** [comment]
Related issue: #1468.

@rt4914: is this only describing the configuration change issues or additional landscape support? I'm wondering if we should split this up since only the particularly bad parts should black alpha (e.g. submit button state being wrong), but others can wait until later (e.g. pending answer being lost on rotation).

**Comment by rt4914** [comment]
Filed smaller issues 
#1591 
#1592
#1593
#1594
#1595

Therefore closing this issue.
