### ISSUE TITLE
Preferences & help should work in the exploration player overflow

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1459]

**Comment by anandwana001** [comment]
@BenHenning @rt4914 If this below gif flow looks satisfying to you, I can send a PR for this. 
Did one minor change, if a user is coming to `Help` or `Options` from `exploration` then the toolbar will have back button rather than hamburger icon for navigation drawer. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25057618/88047933-0b9f8200-cb70-11ea-9dec-9f03bbbf77cf.gif)

**Comment by rt4914** [comment]
@anandwana001 Please directly create PRs and send them for review. Thanks.

**Comment by anandwana001** [comment]
Sure, that will be easy to test. Thanks.
