### ISSUE TITLE
Topic Lesson items getting repeated

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1484]
**Describe the bug**

**To Reproduce**
1. Uninstall the app
2. Click on `First Test Topic`
3. Click on `Lessons`
4. Expand on `Second Story`
5. Click on `Second Exploration` (mostly nothing will load in new screen)
6. Click on `back arrow` in Toolbar 
7. You will notice that the lesson items are repeating.

**Expected behavior**
Lesson items should not repeat.

**Screenshots**
![Screenshot_1595008736](https://user-images.githubusercontent.com/9396084/87816645-4dd17680-c885-11ea-8b83-868154fbb46a.png)

**Comment by anandwana001** [comment]
@rt4914  I think this is happening because when we are in Exploration and press back and a dialog asks if we need to leave and progress will not be saved, then clicking on leave will start the TopicActivity again which set the TopicFragment and TopicLessonFragment and data will be subscribing again.

One more thing I find after debugging is that when we are on the TopicLessonFragment (Screen) and click on any lesson to start, `itemList.add()` calls again and copy the data to the list. The item should be 3 only but after copy, it grows to 6. 
<img width="1397" alt="Screenshot 2020-07-21 at 21 27 04" src="https://user-images.githubusercontent.com/25057618/88077739-381bc400-cb99-11ea-88a5-bbb9d647b75a.png">

`ExplorationActivityPresenter`
<pre>
private fun backPressActivitySelector(backflowScreen: Int?) {
    when (backflowScreen) {
      ParentActivityForExploration.BACKFLOW_SCREEN_STORY.value -> activity.startActivity(
        StoryActivity.createStoryActivityIntent(context, internalProfileId, topicId, storyId)
      )
      ParentActivityForExploration.BACKFLOW_SCREEN_LESSONS.value -> activity.startActivity(
        TopicActivity.createTopicPlayStoryActivityIntent(
          activity,
          internalProfileId,
          topicId,
          storyId
        )
      )
      <b>else -> activity.startActivity(
        TopicActivity.createTopicActivityIntent(
          context,
          internalProfileId,
          topicId
        )
      )</b>
    }
  }
</pre>

`TopicLessonsFragmentPresenter`
<pre>
private fun subscribeToTopicLiveData() {
    topicLiveData.observe(
      fragment,
      Observer<Topic> {
        if (it.storyList.isNotEmpty()) {
          it.storyList!!.forEach { storySummary ->
            if (storySummary.storyId == storyId) {
              val index = it.storyList.indexOf(storySummary)
              currentExpandedChapterListIndex = index + 1
            }
          }
          <b>itemList.clear() // adding this will refill the data after clearing, but back arrow require double tap. </b>
<b>Should we update the way we are transitioning between activity?</b>
          itemList.add(TopicLessonsTitleViewModel())
          for (storySummary in it.storyList) {
            itemList.add(StorySummaryViewModel(storySummary, fragment as StorySummarySelector))
          }
          val storySummaryAdapter =
            StorySummaryAdapter(
              itemList,
              this as ChapterSummarySelector,
              expandedChapterListIndexListener,
              currentExpandedChapterListIndex
            )
          binding.storySummaryRecyclerView.apply {
            adapter = storySummaryAdapter
          }
          if (storyId.isNotEmpty())
            binding.storySummaryRecyclerView.layoutManager!!.scrollToPosition(
              currentExpandedChapterListIndex!!
            )
        }
      }
    )
  }
</pre>

**Comment by rt4914** [comment]
@anandwana001 Can you please create a PR, so that I can actually check this on a branch. Also, generally prefer creating PRs instead of mentioning code in the issue.

**Comment by anandwana001** [comment]
Sure, I will send a PR for review, that will be easy to test.
