### ISSUE TITLE
Make intent/bundle/saved/tags instance keys consistent.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1587]
The keys should be consistent in intents, bundles, tags, etc. They should mainly follow below mentioned structure.

For fragments:
`<PROPERTY_NAME>_ARGUMENT_KEY = "<FileName>.<property_name>"`
Example: `INTERNAL_PROFILE_ID_ARGUMENT_KEY = "SampleFragment.internal_profile_id"`

For activities:
`<PROPERTY_NAME>_EXTRA_KEY = "<FileName>.<property_name>"`
Example: `INTERNAL_PROFILE_ID_EXTRA_KEY = "SampleActivity.internal_profile_id"`

For saved instances:
`<PROPERTY_NAME>_SAVED_KEY = "<FileName>.<property_name>"`
Example: `INTERNAL_PROFILE_ID_SAVED_KEY = "SampleActivity.internal_profile_id"`

**Comment by The-Pascal** [comment]
@rt4914 I would like to work on this issue.

**Comment by rt4914** [comment]
> @rt4914 I would like to work on this issue.

> @rt4914 I want to work on this issue.

Hello @The-Pascal 
Thanks for showing interest. Before we assign you issue to work on please sign the CLA and fill the survey form mentioned here https://github.com/oppia/oppia-android/wiki

Once done, we can assign you issues to work on.

**Comment by janewaitara** [comment]
rt4914 I would like to work on this issue

**Comment by janewaitara** [comment]
@rt4914  I would like to work on this issue

**Comment by rt4914** [comment]
> @rt4914 I would like to work on this issue

@janewaitara Assigned. Thanks.

**Comment by janewaitara** [comment]
## SAVED INSTANCE KEYS - Fixed in #2064 
 - [x] HintsAndSolutionDialogFragment
 - [x] AppLanguageFragment
 - [x] AudioLanguageFragment
 - [x] OptionsActivity
 - [x] TopicLessonsFragment
 - [x] AdministratorControlsActivity

## INTENT KEYS 
### Options and Player Packages - Fixed in #2066 
 - [x] OptionsFragment 
 - [x] StateFragmentTestActivity 
 - [x] OptionsActivity  
 - [x] AppLanguageActivity     

### Profile and Settings.profile packages - Fixed in #2106 
 #### Profile package
 - [x] AddProfileActivity 
 - [x] AdminAuthActivity 
 - [x] AdminPinActivity 
 - [x] PinPasswordActivity 
 #### Settings Profile
 - [x] ProfileEditActivity 
 - [x] ProfileRenameActivity 
 - [x] ProfileResetPinActivity 


### Drawer, Testing and Topic packages - Fixing in progress
#### Drawer package
 - [x] NavigationDrawerFragmentPresenter
#### Testing
 - [x] AudioFragmentTestActivity
#### Topic
 - [x] TopicActivity
 - [x] QuestionPlayerActivity

**Comment by yurilev** [comment]
Can I work on the remaining files?

**Comment by janewaitara** [comment]
> Can I work on the remaining files?

@yurilev  I'm currently working on the files

**Comment by yurilev** [comment]
I'm sorry, I asked because no one was currently assigned.

**Comment by ayush0402** [comment]
I would like to work on this issue.

**Comment by prayutsu** [comment]
Assigning this to you @ayush0402 :)

**Comment by anandwana001** [comment]
@ayush0402 any update on this?

**Comment by ayush0402** [comment]
@anandwana001 I am working on other issue right now.

**Comment by anandwana001** [comment]
Thanks for the update, unassigned you for now. Let me when start working on this again, I will assign you back.
