### ISSUE TITLE
Introduce shimmer effect for loading screens

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1590]
Introduce shimmer effect so that when we are fetching the data in the background we can make sure that Ui does not look bad.

https://facebook.github.io/shimmer-android/

**Comment by rt4914** [comment]
This work item is non-blocking till September 2020 end.

**Comment by prayutsu** [comment]
@rt4914 I would like to work on this issue.

**Comment by aggarwalpulkit596** [comment]
@rt4914 I'll discuss a few things regarding that i have got some ideas which can make this quite dynamic throughout application

**Comment by aggarwalpulkit596** [comment]
@prayutsu i would suggest to take up some beginners issues first to get familiar with project, things like this would require a proper design doc to start implementation.

**Comment by prayutsu** [comment]
> @prayutsu i would suggest to take up some beginners issues first to get familiar with project, things like this would require a proper design doc to start implementation.

Okay, sure!

**Comment by prayutsu** [comment]
@aggarwalpulkit596 can you please help me in identifying the same?

**Comment by aggarwalpulkit596** [comment]
Let me mark some good first issue

**Comment by aggarwalpulkit596** [comment]
@prayutsu https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by rt4914** [comment]
@aggarwalpulkit596 Thanks for helping @prayutsu .

**Comment by MohitGupta121** [comment]
@rt4914 Is this issue is still open?

**Comment by rt4914** [comment]
@BenHenning Can this issue be worked on, or it needs more product details ? cc: @seanlip

**Comment by seanlip** [comment]
I'm not particularly convinced that it needs to be done -- I think this is really a design question. I haven't actually seen many apps that do this though.

@rt4914 You mention that this is "to ensure the UI does not look bad". Could you please provide some examples of what the "bad UI" looks like? Then I can help take this forward.

**Comment by MohitGupta121** [comment]
@seanlip actually I implemented shimmer effect in one project. So I share recording of that just for example.

https://user-images.githubusercontent.com/76530270/158065537-8558a79d-c9f4-40ee-a304-807034d7de84.mp4

@rt4914 you thinking about this type or something else?

**Comment by seanlip** [comment]
Thanks -- to clarify though, I know what the shimmer effect looks like! My main question is what the alternative is (i.e. what does not doing it look like).

**Comment by MohitGupta121** [comment]
> Thanks -- to clarify though, I know what the shimmer effect looks like! My main question is what the alternative is (i.e. what does not doing it look like).

Okay that.

**Comment by BenHenning** [comment]
> Thanks -- to clarify though, I know what the shimmer effect looks like! My main question is what the alternative is (i.e. what does not doing it look like).

@seanlip Essentially all data that shows up on screens in the app is technically asynchronous. For most devices, this loads fast enough that the user doesn't notice any abrupt UI changes. On slower devices (or with artificial delays, which is something we could consider adding) it's much more noticeable. While we're not particularly attached to adding a shimmer in particular, having a general way to visually communicate to the user that something is loading and that the page will soon change seems important. Does this help provide clarity?

> @BenHenning Can this issue be worked on, or it needs more product details ? cc: @seanlip

@rt4914 I also think this is primarily a design question. I'm not actually sure we even need a shimmer, but because of the possibility of screens taking a while to load it does seem worthwhile to figure out a general loading UX pattern (including for a11y users).

To others on this thread: I also want to emphasize that this is likely going to become a project that requires a technical design document. It won't be a small change since we need to figure out several things, including:
- How to build a general loading UX (which is heavily design dependent)
- Do an accounting of all screens that will require this functionality
- How to integrate that general loading UX across the app for different screens
- Develop a way to tie the loading state to all UI elements which are asynchronous (which is probably just all DataProviders and/or LiveDatas)
- Figure out how this ties to databinding
- Figure out the accessibility version of the loading interstitial
- Add metrics to measure per-screen latency (since we want to minimize how much this loading interstitial is shown)
- Ensure the interstitial isn't unnecessarily showing for very short amounts of time (which might cause even more visual noise)

And probably other things I haven't considered yet.

FWIW, I actually don't think this is a high priority task at the moment. I think this may be worth moving to the team's product icebox for the time being. It's an important feature to introduce to reduce long-term user-perceived jank and make the app UX more predictable, but we have much higher priority core functionality to add first which will add more impact.

**Comment by seanlip** [comment]
Thanks for the detailed explanation, Ben. Sounds good -- I have updated the priority and labels accordingly. I also agree with the assessment that this is not a high-priority task and that more design work is needed here.

**Comment by rt4914** [comment]
As per my latest experience with the app, we don't need Shimmer effect as of now. Also, there haven't been any issues filed based on loading state. The app has been working fine for a lot of devices and therefore introducing Shimmer effect as of now does not make sense.
We might need to introduce loading state but that should be a separate issue and also as and when we think that we actually need it. 
Closing this issue.
