### ISSUE TITLE
StateFragmentLocalTest & other Robolectric tests hanging on develop

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1608]
**Describe the bug**
Various Robolectric tests seem to indefinitely hang & not run on the latest develop branch.

**To Reproduce**
1. Check out develop
2. Run StateFragmentLocalTest
3. Experience that the test indefinitely hangs

**Expected behavior**
The test should start after ~5-10 seconds and then run through all tests (each test should run every 1-2 seconds).

**Device**
- Android Studio 4.0.1

**Additional context**
Observed this on develop hash b7016a8cd92388dceda151dca07f672effb5262c.

**Comment by BenHenning** [comment]
This is blocking alpha work, so I'm looking into this. Doing a binary search.

**Comment by BenHenning** [comment]
I noticed that this is failing on b7016a8cd92388dceda151dca07f672effb5262c but working on 0b5858098c23483e4550b64789ee99a0d4135ae8.

**Comment by BenHenning** [comment]
It seems like this was introduced in 41eb10bd0c04596cb18c354da7db7268121a09be. FYI @MohamedMedhat1998 & @rt4914.

**Comment by BenHenning** [comment]
I'm guessing the flashing animation added in https://github.com/oppia/oppia-android/pull/1475/files#diff-41d583216532071dbb2dfc75191d51f6 is causing some sort of issue with Robolectric. @MohamedMedhat1998 did you run all app module tests when making these changs?

**Comment by BenHenning** [comment]
Unfortunately, there are changes in both #1475 and #1526 that are stacked, so a manual revert is needed. I'm choosing to revert over fixing forward since the fix isn't actually clear, and this is blocking alpha work.

**Comment by BenHenning** [comment]
Confirming that reverting the animation fixes ``StateFragmentLocalTest``. Sending out PR to revert momentarily.

**Comment by BenHenning** [comment]
Also: I think this only affects state fragment tests given the nature of where the animation exists.

**Comment by MohamedMedhat1998** [comment]
> I'm guessing the flashing animation added in https://github.com/oppia/oppia-android/pull/1475/files#diff-41d583216532071dbb2dfc75191d51f6 is causing some sort of issue with Robolectric. @MohamedMedhat1998 did you run all app module tests when making these changs?

@BenHenning I haven't tried running all the tests after adding the animation because I didn't change the core implementation.  


> Confirming that reverting the animation fixes `StateFragmentLocalTest`. Sending out PR to revert momentarily.

I have checked the develop and found that the current develop doesn't contain the animation as you mentioned.  
I have also checked #941 and it was added to milestone 3.  
Should I try to implement it in a different way?

**Comment by BenHenning** [comment]
Sorry, which animation @MohamedMedhat1998? Note that #1609 was a reversion, so the changes shouldn't be in develop anymore.

**Comment by anandwana001** [comment]
> /cc @anandwana001 who first reported this

I was trying to run this file test cases but failed and then I asked rajat thinking might my AS is giving some issues, but he got this failure and delayed issue too, and then I asked in hangout group.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> Sorry, which animation @MohamedMedhat1998? Note that #1609 was a reversion, so the changes shouldn't be in develop anymore.

@BenHenning I mean that the radar animation was removed from the develop because it was causing some problems with test cases. Now, the issue #941 (Add radar effect in Hints and Solution) was added to milestone 3 of my project.  
The question is, should I figure out a new implementation of the radar animation, or I should wait till you discuss with Chantel as @rt4914 mentioned in yesterday's meeting?
