### ISSUE TITLE
List of subtopics in practice tab duplicates after playing an exploration

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1635]
**Describe the bug**
The list of subtopics in the practice tab duplicates after playing an exploration.

**To Reproduce**
1. Navigate to the fractions topic
2. Open practice ab
3. Observe one list of subtopics
4. Go to lessons
5. Start a lesson
6. Navigate back to the topic
7. Navigate to the practice tab
8. Observe that there are now two duplicate lists of subtopics

**Expected behavior**
The list of subtopics shouldn't duplciate.

**Screen recording**
![duplicate_subtopic_lists](https://user-images.githubusercontent.com/12983742/90083438-5fad0a80-dcc7-11ea-9293-3c881b317313.gif)

**Device**
- Device: Pixel XL
- SDK version: 29

**Additional context**
This seems to repro on a relatively up-to-date build.

**Comment by BenHenning** [comment]
@rt4914 is this maybe a recent regression? I won't have time to root cause this; can you look into finding which PR caused this?

**Comment by rt4914** [comment]
@BenHenning 
I did investigate the issue and I have found from the [commit history](https://github.com/oppia/oppia-android/commit/08235de9cf62f5fe9c1f3d52f6aa42291990e11d#diff-cdeafa260ef8ca6af727c051cbf9b494) that it was incorrect from the very start.

The reason why were we not able to observe this issue earlier is because earlier we had almost 11 subtopics which means that even if it got repeated, because it was a long list unless and until we don't scroll we cannot see that issue. And recently we optimised to these 4 subtopics only which makes it easy to observe this issue in `Practice` tab.

The solution is just to be clear the `itemList` before adding items to it.

Also although the `Revision` tab is not observing this issue because its not possible to create that scenario in current develop but I have still added `itemList.clear()` in that implementation too because it might happen in future we make some changes in domain layer which triggers this issue similar to `Practice`.
