### ISSUE TITLE
Introduce Pre-Commit hooks

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1837]
**Is your feature request related to a problem? Please describe.**
Currently, we have Ktlint run over GitHub Actions and at each commit, the developer has to resolve if any error occurs. 

**Describe the solution you'd like**
If we introduce the pre-commit hook, the Ktlint will run on developer's local machine and the issue will be resolved before coming to PR. 

**Additional context**
Currently, we have Ktlint and we have to add more in the below list once other linters added. 
- [ ] Ktlint
- [ ] Buildifier

**Start working on these after the gets added**
- [ ] Checkstyle
- [ ] XML

**Comment by BenHenning** [comment]
Note that one challenge here is that pre-commit hooks must be setup locally by the team member, and we don't yet have any part of our starting workflow that involves scripts. This might change with Bazel, but we ideally should figure out a way to integrate populating the pre-commit hooks as part of the build process via Android Studio since most contributors will probably only be using Android Studio.

**Comment by anandwana001** [comment]
Duplicate of #637 
Closing this one
