### ISSUE TITLE
Thoroughly test ItemsSelectionIsProperSubsetOfRuleClassifier

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1900]
Since the ItemsSelectionIsProperSubsetOfRuleClassifier was copied from Oppia web, it didn't have corresponding tests added to verify correctness. These should be ported over from Oppia web as well to ensure that each classifier has working functionality.

Useful reference - https://github.com/oppia/oppia-android/tree/develop/domain/src/test/java/org/oppia/android/domain/classify/rules

**Comment by soamOne** [comment]
Hey @Sarthak2601 , I would like to work on this issue. But I do not really know how to thoroughly test stuff, could you tell me a bit about it?

**Comment by BenHenning** [comment]
@soamOne assigning this to you.

To start, I suggest you take a look at https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#learning-how-to-write-good-tests and the other parts of that page. Further, you can also reference other similar test suites (such as [MultipleChoiceInputEqualsRuleClassifierProviderTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/multiplechoiceinput/MultipleChoiceInputEqualsRuleClassifierProviderTest.kt) since multiple choice is pretty similar to item selection) to get an idea of:
1. How the tests are actually written
2. What sorts of behaviors might be worth testing

If you're unsure which tests to write, I suggest writing just a single test for 1 behavior of ItemSelectionIsProperSubsetOfRuleClassifier and sending out a draft PR for that single test to get feedback.

**Comment by anandwana001** [comment]
unassigning @soamOne as no update.

**Comment by FareesHussain** [comment]
I'm working on this
