### ISSUE TITLE
Temporary disable the RTL support

### ISSUE THREAD

**Issue by MohamedMedhat1998** [oppia/oppia-android#1902]
Currently, we don't have mocks for RTL layouts and the app looks bad in the RTL devices, so we need to disable RTL support temporary.

**Comment by rt4914** [comment]
@BenHenning Should we do this or not?

**Comment by BenHenning** [comment]
Given that the app isn't yet localized, do we actually expect people to be using it with RTL mode on? Also note that our only users are ones that we select for the alpha, so we can focus on testing with people who don't require RTL mode for now.

I'm not actually an advocate of disabling it since we should be working to bring in RTL support rather than ignore it.

Also, do we need mocks for RTL? My expectation is that RTL and LTR should match, just be reversed according to https://material.io/design/usability/bidirectionality.html.

**Comment by MohamedMedhat1998** [comment]
> Given that the app isn't yet localized, do we actually expect people to be using it with RTL mode on? Also note that our only users are ones that we select for the alpha, so we can focus on testing with people who don't require RTL mode for now.
> 
> I'm not actually an advocate of disabling it since we should be working to bring in RTL support rather than ignore it.

Got it

> Also, do we need mocks for RTL? My expectation is that RTL and LTR should match, just be reversed according to https://material.io/design/usability/bidirectionality.html.

That's true but it doesn't always work as expected. For example, some items are designed to look well in the case of LTR (like the hints icon) but when they are on the RTL, they look awkward.

**Comment by BenHenning** [comment]
Awkward in what way? Ideally, our existing UI should be conducive to RTL scenarios though some specific situations might need tweaking (icons specifically come to mind which is also why I linked to the bidirectionality page above). Beyond that, we can always ask Chantel for cases in which we're unsure.

**Comment by MohamedMedhat1998** [comment]
![Screenshot_2020-10-01-12-32-25](https://user-images.githubusercontent.com/8533363/94798790-65c78980-03e2-11eb-88d8-a6c8e0706bc5.png)
The round corner is incorrect here.  
There are only some items that need to change, but I think it isn't a big deal.  
The hint icon is just an example, but as you said, for the RTL, we don't need new mocks

**Comment by BenHenning** [comment]
Ah I see, that is what I meant that the existing UIs should be conducive. That screenshot shows a clear bug that we're incorrectly fixing the corner to the right rather than the start, and directional icons may be wrong in that picture.

We may legitimately have cases where we need mocks for RTL layouts, but I'm hoping they are minimal. We should preferably have general design guidelines for RTL that developers can follow to make sure their layouts are properly designed for both RTL and LTR.

**Comment by MohamedMedhat1998** [comment]
I agree.

**Comment by rt4914** [comment]
Closing this issue as we are in process of supporting all screens with RTL.
