### ISSUE TITLE
Fix NavigationDrawerTestActivityTest for Robolectric 

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1968]
Currently, NavigationDrawerTestActivityTest are passing on Espresso but they should also pass on Robolectric. Fix these below mentioned files to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1).

**Comment by FareesHussain** [comment]
Please assign this to me
and what tests are left to be fixed

**Comment by anandwana001** [comment]
@FareesHussain all the tests which are marked ignore are left. This is one of the complex issue we have. In order to solve this issue please check this wiki section and all the tests should pass on both, espresso and robolectric. 

https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#tips-to-run-test-cases-in-both-espresso-and-robolectric

**Comment by FareesHussain** [comment]
ok then I'll check if I can do that
