### ISSUE TITLE
LogUploadWorkerTests sometimes fail on github actions.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2032]
Issue Reference: https://github.com/oppia/oppia-android/pull/1983#issuecomment-712896420

Possible solution reference: https://developer.android.com/topic/libraries/architecture/workmanager/advanced/coroutineworker

<img width="1253" alt="Screenshot 2020-10-20 at 7 58 26 PM" src="https://user-images.githubusercontent.com/9396084/96904445-c2cfd000-14b4-11eb-98b0-314fae5813e0.png">

**Comment by BenHenning** [comment]
New bug report:

**Describe the bug**
LogUploadWorkerTest is sometimes flaky when run with Bazel on CI. Per #2642, we observed this failure:

```
==================== Test output for //domain:src/test/java/org/oppia/android/domain/oppialogger/loguploader/LogUploadWorkerTest:
JUnit4 Test Runner
.Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
.System.logW: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.java.lang.Throwable: Explicit termination method 'close' not called
E
Time: 6.538
There was 1 failure:
1) testWorker_logException_withoutNetwork_enqueueRequest_verifySuccess(org.oppia.android.domain.oppialogger.loguploader.LogUploadWorkerTest)
expected: SUCCEEDED
but was : RUNNING
	at org.oppia.android.domain.oppialogger.loguploader.LogUploadWorkerTest.testWorker_logException_withoutNetwork_enqueueRequest_verifySuccess(LogUploadWorkerTest.kt:167)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

FAILURES!!!
Tests run: 2,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.
```

**To Reproduce**
Steps to reproduce the behavior:
1. Check out the repository
2. Make sure Bazel is set up locally (see [wiki page](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) for instructions)
3. Verify Bazel is working by building the test: ``bazel build //domain:src/test/java/org/oppia/android/domain/oppialogger/loguploader/LogUploadWorkerTest``
4. Run the test at least 30 times (this leads to a 90% chance of encountering at least 1 failure): ``bazel test --runs_per_test=30 -- //domain:src/test/java/org/oppia/android/domain/oppialogger/loguploader/LogUploadWorkerTest``
5. Observe that the test fails at least once with a similar failure the one above

**Expected behavior**
The test should pass with at least 100 runs in a row.

**Screenshots**
N/A

**Device**
N/A -- this is a Robolectric test

**Additional context**
Investigating this issue seems like a investigation project for contributors, but the problem and solution may be more complicated. I suggest starting with trying to figure out what the root cause of the issue is before attempting to find a solution.

**Comment by BenHenning** [comment]
I think I have a prospective fix.

Also related: #3714.
