### ISSUE TITLE
[RTL] High-fi Navigation Drawer

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2268]
`Navigation Drawer` needs RTL support as shown in below screen.
![HP (Side Menu) – RTL](https://user-images.githubusercontent.com/9396084/102314248-20a20500-3f98-11eb-82b8-0439aa3b509d.png)

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by varunvjha** [comment]
I want to work on this issue.

**Comment by rt4914** [comment]
> I want to work on this issue.

Thanks for showing interest @varunvjha . Before we get started please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by varunvjha** [comment]
> > I want to work on this issue.
> 
> Thanks for showing interest @varunvjha . Before we get started please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

I have completed the abovementioned tasks, can you assign me this issue now?

**Comment by srikanthkb** [comment]
Hi @rt4914 , @anandwana001, @FareesHussain,
Please check the following screenshots for Phone and tablet: 
****For Phone:**** 
****Portrait:**** 
![image](https://user-images.githubusercontent.com/36214903/103407697-948e0100-4b85-11eb-87e0-7106eab62de0.png)

**Landscape:**
![image](https://user-images.githubusercontent.com/36214903/103407726-b2f3fc80-4b85-11eb-8a3a-8a8647cfe694.png)

**For Tablet:**
Portrait: 
![image](https://user-images.githubusercontent.com/36214903/103407753-cb641700-4b85-11eb-8bc5-c065330bdde4.png)

Landscape:
![image](https://user-images.githubusercontent.com/36214903/103407769-d6b74280-4b85-11eb-9592-414807c18ef8.png)


I think this issue is not observed anymore. Provide your inputs on this.

**Comment by FareesHussain** [comment]
@Srikanth-Kb This is actually a RTL (Right to Left) related issue please have a look at
https://github.com/oppia/oppia-android/wiki/RTL-Guidelines
for Reference to solve RTL related issues

**Comment by srikanthkb** [comment]
> @Srikanth-Kb This is actually a RTL (Right to Left) related issue please have a look at
> https://github.com/oppia/oppia-android/wiki/RTL-Guidelines
> for Reference to solve RTL related issues

Ok.. Noted.. Thank you for the reference

**Comment by rt4914** [comment]
@FareesHussain Thanks.
