### ISSUE TITLE
Optimise TextInputLayout in add_profile_activity

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2460]
Remove `android:textDirection="locale"` in `TextInputLayout` from the following files
 - layout/add_profile_activity
 - layout-land/add_profile_activity
 - sw600dp/add_profile_activity
 - sw600dp-land/add_profile_activity

**Comment by GowthamGoush** [comment]
I would like to work on this issue, could you assign this to me?

**Comment by dipu989** [comment]
@FareesHussain Can you please assign this to me?

**Comment by rt4914** [comment]
> I would like to work on this issue, could you assign this to me?

@GowthamGoush Thanks for showing interest. Please, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on. Once this is done, we can assign you issues to work on. For now this issue is assigned to @dipu989 .
