### ISSUE TITLE
Revealing second hint after orientation change before the timer

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#2476]
**Describe the bug**
For the questions with more than one hint, the second hint is revealed before 10 seconds after orientation change

**To Reproduce**
1. Go to `What is a Fraction` story inside `Fractions`
2. click on `continue`, `continue`, `Three fifths`, `Four sevenths`, `2nd option (green)`
3. Here select the option `7/2` twice and reveal the hint
4. go back to question
5. change to the landscape
6. see the 2nd revealed hint

**Expected behavior**
Only reveal second hint after 10sec timer

**Comment by FareesHussain** [comment]
cc: @BenHenning

**Comment by BenHenning** [comment]
So I think that this might because of [this line](https://github.com/oppia/oppia-android/blob/74db288/app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt#L218). It seems like in some cases it might force a new hint to be shown when compute() is called (which will happen on configuration change since the adapter & list is recreated). I'm guessing that we need to build in some additional check to ensure we're only ever showing a hint when there's legitimately a new one to show.

**Comment by BenHenning** [comment]
We should also make sure that this specific cases & related cases are thoroughly tested, too.

**Comment by FareesHussain** [comment]
@BenHenning Can we do something like restart the timer after orientation change

**Comment by imraghav20** [comment]
@FareesHussain can I work on this issue?

**Comment by imraghav20** [comment]
I tried to make few changes, although the issue is still not solved.
Should I share the changes in code in a comment or make a PR to review and suggest appropriate changes.

**Comment by FareesHussain** [comment]
I'm sorry I forgot to assign myself actually I'm currently working on it
