### ISSUE TITLE
Marquee restarts automatically in certain scenarios.

### ISSUE THREAD

**Issue by Luffy18346** [oppia/oppia-android#2581]
**Describe the bug**
In ideal case, Marquee should only start when user click on toolbar but Marquee restarts automatically in certain scenarios after Marquee stops for the first time.

**To Reproduce**

General Steps for all below mentioned cases:
1) Go to The Meaning of Equal Parts exploration
2) Go to Second state. Note that the title is not moving.
3) Click on Toolbar and Marquee starts moving.

Case 1:
4) Once marquee stops, pull down notification bar of your mobile from top to bottom and then pull up, you will see Marquee moving again without clicking the toolbar.

Case 2:
4) Once marquee stops, click on EditText, Marquee starts moving again. Now wait for it to stop don't do anything.
Also after the marquee stops, then press back button to close the keyboard and you will see Marquee starts moving again

Case 3:
4) Once marquee stops, click on hint button, Marquee starts moving again.

Case 4:
4) Once marquee stops, click on close button at top-left, Marquee starts moving again.

Case 5:
4) Once marquee stops, on clicking it again, Marquee won't start no matter how many times user clicks on the toolbar.

**Expected behavior**
Marquess effect should start only on click on the toolbar and not automatically & it should starts every time user clicks on the toolbar after marquee stops moving.

For reference please refer to this issue: #1770

**Comment by Prince-kushwaha** [comment]
can is work on this issue

**Comment by Prince-kushwaha** [comment]
@FareesHussain  @Luffy18346  can i work on this issue

**Comment by Sparsh1212** [comment]
If this is still up for grab then please assign it to me @FareesHussain .

**Comment by FareesHussain** [comment]
@Prince-kushwaha any updates on this?

**Comment by FareesHussain** [comment]
> If this is still up for grab then please assign it to me @FareesHussain .

@Sparsh1212 as you are assigned to [4 other issues](https://github.com/oppia/oppia-android/issues/assigned/Sparsh1212). I would recommend you to wait for those to get merged first.

**Comment by Sparsh1212** [comment]
> > If this is still up for grab then please assign it to me @FareesHussain .
> 
> @Sparsh1212 as you are assigned to [4 other issues](https://github.com/oppia/oppia-android/issues/assigned/Sparsh1212). I would recommend you to wait for those to get merged first.

Actually, I have initiated the PRs for the first two issues. @fsharpasharp  has asked to wait for a while ([comment](https://github.com/oppia/oppia-android/pull/2700#issuecomment-780822120)) for these Bazel-related issues because some more research has to be done on them, so I think that will take some time to get reviewed.  And I have unassigned myself from the 3rd issue. So, I currently have only 1 active issue of which I have already initiated the PR.

**Comment by Sparsh1212** [comment]
@rt4914 
https://stackoverflow.com/a/44795525
As per the above StackOverflow answer, it seems that the Marquee effect is restarting because TextView loses its focus.
There were two approaches to fix this and I tried both of them:
1. By wrapping the TextView inside a Linear Layout ([Ref](https://stackoverflow.com/a/21570570))
2. By setting fixed dimensions (instead of `wrap_content` or `fill_parent`) on the `layout_width` and `layout_height`. ([Ref](https://stackoverflow.com/a/13841982))
But none of them seems to fix the problem that we are facing in this issue. The Marquee effect restarts again in the 5 cases.
Can you please take a look at this and please guide me on how should I approach this now? because none of the two fixes seems to work.

**Comment by rt4914** [comment]
@Sparsh1212 That's exactly the issue. I tried to find solution but nothing seems to work for this. Me, Akash and few more contributors have tried solving this issue in past too and we haven't been able to fix it yet. I am afraid this might need more research from your side. Also, if this really becomes hard its completely fine to un-assign yourself and move on to some other issue.

**Comment by Sparsh1212** [comment]
> @Sparsh1212 That's exactly the issue. I tried to find solution but nothing seems to work for this. Me, Akash and few more contributors have tried solving this issue in past too and we haven't been able to fix it yet. I am afraid this might need more research from your side. Also, if this really becomes hard its completely fine to un-assign yourself and move on to some other issue.

Thank you. I will try to do a bit more research on this once again and if I will still not be able to find any fix for this, then will unassign myself.
