### ISSUE TITLE
Resolve ktlint max line in OptionsFragmentPresenter

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2715]
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name.
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the line of code under 100 char length.

Where to Start?
1. Complete all installation steps before starting with this issue - https://github.com/oppia/oppia-android/wiki#installation
2. 
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/main/java/org/oppia/android/app/options/OptionsFragmentPresenter.kt#L93

Breaking line of code into multiple line to fix this issue. 
```kotlin
  private fun createRecyclerViewAdapter(
    isMultipane: Boolean
  ): BindableAdapter<OptionsItemViewModel> {
```

**Comment by adit19shah** [comment]
I'm interested in working on this issue.

**Comment by FareesHussain** [comment]
@adit19shah Thanks for showing interest in oppia. Please check out our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by adit19shah** [comment]
@FareesHussain Done.

**Comment by FareesHussain** [comment]
@adit19shah Please fill the CLA too.

**Comment by adit19shah** [comment]
@FareesHussain I've already filled it.

**Comment by FareesHussain** [comment]
It doesn't show here can you please re-check if you've filled the CLA, 
I think you've only filled the survey

**Comment by adit19shah** [comment]
![image](https://user-images.githubusercontent.com/58650668/107881213-66803880-6f09-11eb-93b4-f19fba8b44f8.png)
 
Yupp, I rechecked it, it's showing me this message "You've already responded". Just to clarify, I had filled both these forms back in December 2020 but wasn't able to continue at that time owing to some personal reasons. Since the survey form was editable, I edited it again today but CLA form isn't editable and doesn't allow responding more than once.
