### ISSUE TITLE
Audio is being played even after hiding The audio icon in exploration

### ISSUE THREAD

**Issue by ksog66** [oppia/oppia-android#2893]
**Describe the bug**
In Exploration activity while listening to the audio, if we double click the hide audio icon within 2 second , audio will still play even after icon is hidden. 

**To Reproduce**
1. Go to Any lesson of any topic and play the chapter 
2. Click on audio icon on top of toolbar twice within 2 second.
3. See it will play the audio, even the audio fragment will be hidden

**Expected behavior**
It should have hide the audiobar fragment and not play the audio.

**Screenshots**
https://user-images.githubusercontent.com/70816971/110897373-58181780-8323-11eb-8905-7bf20e3b37c5.mp4

**Device**
- Realme 1 
- SDK version 28

**Comment by ArpitShukIa** [comment]
Assign to me, I would like to work on this.

**Comment by anandwana001** [comment]
@ksog66 is this a similar issue - https://github.com/oppia/oppia-android/issues/1801
Please confirm

**Comment by ksog66** [comment]
@anandwana001 looks like the same issue but step to reproduce are not very clear, should i close this issue then.

**Comment by anandwana001** [comment]
@ksog66 Let's see if the PR by @ArpitShukIa is solving both the issues.

**Comment by BenHenning** [comment]
Per https://github.com/oppia/oppia-android/issues/1801#issuecomment-762203630 the issue seems the same. This issue is also potentially quite a bit harder than it seems at the surface. We need to be properly synchronizing audio state across threads--my concern is that any fixes at this point will still leave other holes that need to be patched without a systemic fix.

Closing this issue in favor of #1801. I'll update that issue's description to mention that it's also covering the steps mentioned here.
