### ISSUE TITLE
Images are cut off in revision cards

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3005]
**Describe the bug**
Images are not being properly sized to the available space and are instead being rendered at their native resolution. On some screens, this results in them being cut-off.

**To Reproduce**
1. Navigate to the "Combining Ratios" revision card
2. Observe that the graphics are cut-off when compared with the [web platform](https://www.oppia.org/learn/math/ratios/revision/combining-ratios)

**Expected behavior**
Images should be upscaled/downscaled to fit the screen size.

**Screenshots**
Portrait:
![image](https://user-images.githubusercontent.com/12983742/112372937-a6bb9f00-8c9d-11eb-92e9-c67756b4ddef.png)

Landscape:
![image](https://user-images.githubusercontent.com/12983742/112372988-b6d37e80-8c9d-11eb-9aeb-be59527863b7.png)

If applicable, add screenshots or videos to help explain your problem.

**Device**
- Device being used: Nexus 5X
- SDK version: 27

**Additional context**
This was found during Alpha MR2 testing.

**Comment by E13ctron** [comment]
@BenHenning ,I need some help to work on this, I couldn't find an activity like this in the oppia-android app.

**Comment by E13ctron** [comment]
@BenHenning , could you guide me to reproduce this issue

**Comment by rt4914** [comment]
@Amar-2003 I think it cannot be assigned to you as it needs access to alpha content. Suggest picking up some other issue.

**Comment by E13ctron** [comment]
@rt4914 , ok fine thanks :)

**Comment by adhiamboperes** [comment]
I checked this since it is a similar issue to the other image cropping issues. I took these screenshots from the **playstore beta version** on a device with similar specs as the reporting device, and it seems that the display works fine.

![WhatsApp Image 2022-11-17 at 17 52 21](https://user-images.githubusercontent.com/59600948/202479279-c5bf1814-8274-42ed-bd07-cd3206fc55db.jpeg)
![WhatsApp Image 2022-11-17 at 17 52 20](https://user-images.githubusercontent.com/59600948/202479243-ff1c2921-cf7c-421b-9c09-f5679caffdd0.jpeg)

**Comment by BenHenning** [comment]
Thanks @adhiamboperes! I agree--it looks like this issue has been addressed with past image work (not specific to the recent changes in UrlImageParser, either, if this is working on the current Play Store beta version).
