### ISSUE TITLE
Field Leaks context object

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3084]
**Describe the bug**
![](https://user-images.githubusercontent.com/9396084/114028502-2c427000-9896-11eb-8892-7fedc3a8a53d.png)

**Expected behavior**
Check `CompletedStoryItemViewModel` file. `DownloadsTopicViewModel` is not currently available in the repository.

**Comment by Victor-Titan** [comment]
@anandwana001 @rt4914 The issue is that the class is being used [here](https://github.com/oppia/oppia-android/blob/f9eb3cdcba174fdd78690af33ffe3c7a8b547a10/app/src/main/java/org/oppia/android/app/completedstorylist/CompletedStoryListViewModel.kt#L67) and that is causing the leaked context. One way to solve this might be creating a class object initially and using it. For this we may have to create a separate class which has all parameters except `completedStory` and then creating another class object which can take `completedStory` as a parameter inside the lambda. Once we're done with the lambda, we can delete the first object and hence prevent any leaks.

**Comment by anandwana001** [comment]
@Victor-Titan Could you send aa pr for this?

**Comment by Victor-Titan** [comment]
I'm sorry, my approach doesn't work.

**Comment by ArpitShukIa** [comment]
@anandwana001 Is it a part of [this](https://github.com/oppia/oppia-android/issues/1051) issue?

**Comment by anandwana001** [comment]
Yes, nice find. Closing this issue as this is a part of #1051
