### ISSUE TITLE
Dark theme can be forced on some devices, breaking app UI

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3097]
Few devices like Xiaomi forces the system theme (dark) to the apps that don't support the dark theme.

Example
![image](https://user-images.githubusercontent.com/54740946/114901254-3d5d2500-9e32-11eb-8d49-48820e9b8926.png)

Devices with the same issue:
- Poco X3 (Android 10) @Victor-Titan 
- Redmi K20 PRO (Android 10) @prayutsu 
- Realme 3 (Android 10) @ARJUPTA 
- Redmi note 7 pro (Android 9) @FareesHussain 

How to reproduce (only for few devices)
- Set the system theme to Dark mode 
- Open oppia-android app
- Navigate to Home Activity

**Comment by FareesHussain** [comment]
cc\ @prayutsu @ARJUPTA @Victor-Titan

**Comment by BenHenning** [comment]
Thanks for filing this @FareesHussain! /cc @rt4914 as well.

**Comment by Victor-Titan** [comment]
I think I've found a way to fix this. Assigning myself, will open a Pull Request shortly.

**Comment by ayush0402** [comment]
Closing this as merging dark mode [starter issues](https://github.com/oppia/oppia-android/issues?q=is%3Aissue+in%3Atitle+add+dark+mode+is%3Aopen) will fix this for particular screens.
MIUI forces their own color in case of colors not being separated by day/night files but starter issues will fix this.

Screenshot of AddProfileActivity fixed with above approach: 
(Tested on Redmi K20 Pro running MIUI 12 based on Android 11)
<img src="https://user-images.githubusercontent.com/76056229/155483635-26212945-564b-44c6-bd01-2b7d7ac5c26e.jpg" alt="screenshot" width="250">
