### ISSUE TITLE
Test Segregation in OptionsFragmentTest

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3103]
Currently in `OptionsFragmentTest` tests are working across multiple activities but thats not correct.
Each file should contain tests only related to that file and should not check functionalities of other activities.

Segregate tests of OptionsFragmentTest into 
- OptionsFragmentTest
- AudioLanguageFragmentTest
- AppLanguageFragmentTest

Also we should add more tests to make sure that we are able to hit 100% code coverage for these files which means that if we combine all tests than they should have traversed/used each line written for the functionality.

**Comment by Sparsh1212** [comment]
@rt4914 
I had a look at the `OptionsFragmentTest` file and also ran the tests.
There are a total of three tests which seems to be of other files:
- `testOptionsFragment_audioLanguage_testOnActivityResult()`
- `testOptionsFragment_appLanguage_testOnActivityResult()`
- `testOptionsFragment_readingTextSize_testOnActivityResult()`

These tests basically check the item displayed on the Options Recycler View. That means these tests are checking the functionalities of the Options file only.  Hence, I am actually confused here why do we have to separate these tests from this file, because these are the checks for the functionality of the Options file only. Can you please elaborate or correct me if I have misinterpreted something.

**Comment by rt4914** [comment]
You are correct that they are checking it only on `Options` file but that is getting done by visiting a new activity which is incorrect.
The ideal way to test such cases is by breaking them in two separate tests:
A. check that Options file has correct info and is sending correct intent to ActivityB.
B. check that ActivityB has correct info and is sending back correct information on finishing it.

A will be part of `Options` test file and B will part of separate test file.

**Comment by Sparsh1212** [comment]
@rt4914 Thank you for the clarification. That really helped me.

This is how I am planning to approach this:

**Part-A**
- Write a test in OptionsFragmentTest to check that the correct item is displayed in the recycler view of the Options file. (Repeat this a total of three times to check for App Language, Audio Language, and ReadingTextSize)
- Repeat the above three tests for a configuration change.
- Write a test for clicking an item in the Options Recycler View and check if it is sending the correct intent (Repeat this three times to check for App Language, Audio Language, and ReadingTextSize)
- Also, repeat the above three tests for a configuration change.
This completes part A as suggested.

**Part-B**
- Write a test in AppLanguageFragmentTest to check item displayed in the Recycler view of App Language (Repeat this similarly for AudioLanguage and TextSize Test files)
- Repeat the above test for a configuration change.
- Clicking on any one of the items in the RecyclerView, then pressing the back button and verifying that it has sent back the correct info.

**Comment by Sparsh1212** [comment]
@rt4914 
Here's the update about the Part-B work that I have initiated:
- All the previous tests in `AppLanguageFragmentTest` are removed and these four new tests are added keeping in mind the ideal practice (i.e not to launch the other Activity and only use the Test File Activity): 
  1. `testAppLanguage_selectedLanguageIsEnglish()`
  2. `testAppLanguage_changeConfiguration_selectedLanguageIsEnglish()`
  3. `testAppLanguage_changeLanguageToFrench_selectedLanguageIsFrench()`
  4. `testAppLanguage_changeLanguageToFrench_changeConfiguration_selectedLanguageIsFrench() `
 
- I also tried adding this test:
```kt
   @Test 
   fun testApp_Language_pressBackBtn_SendsBackCorrectInfo(){
      launch<AppLanguageActivity>(createAppLanguageActivityIntent("English")).use {
          testCoroutineDispatchers.runCurrent()
          pressBack()
          intended(hasExtra(MESSAGE_APP_LANGUAGE_ARGUMENT_KEY, "English"))
    }
   }
```
But it is failing in Roboelectric with the error that 0 intends matched.
It looks like the Back press is getting ignored totally.
I also tried many other things to click the back button or to run the `onBackPress` function but nothing seems to work. Can you please take a look at this and guide me on what I am doing wrong here or if this approach isn't correct then how can we achieve checking that it is sending back the correct info on back press through another approach.

- I have not made any changes to `ReadingTextSizeFragmentTest` because currently there is a PR which will propose some changes in this file, so I think it will be better to wait rewriting this file until those changes are merged.

- Will make all the similar changes for `AudioLanguageFragmentTest` once I get a pass on the above changes and the getting back correct info on the back press problem is resolved.  

Thanks!
