### ISSUE TITLE
Less Bottom Margin

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3210]
**Describe the bug**
There is not much bottom margin

**Screenshots**
![Screenshot_1621487843](https://user-images.githubusercontent.com/25057618/118923232-d95ddd00-b958-11eb-838d-c240e4c349ca.png)
![Screenshot_1621487906](https://user-images.githubusercontent.com/25057618/118923292-eed30700-b958-11eb-816c-7e29204c7317.png)
![Screenshot_1621487900](https://user-images.githubusercontent.com/25057618/118923308-f692ab80-b958-11eb-8ad4-21f2af838872.png)

**Comment by anandwana001** [comment]
@rt4914 PTAL
Also, when hint icon visible, the prev button hides.

**Comment by pravesh00** [comment]
Can I work on this?

**Comment by anandwana001** [comment]
Hi @pravesh00 it is assigned to @rt4914 You can look for other good first issues. 
Start here - https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by ishitaojha** [comment]
Hey is the issue fixed or can I give it a try?

**Comment by rt4914** [comment]
> Hey is the issue fixed or can I give it a try?

@ishitaojha This issue is already assigned to me. Can you please select some other issue from [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee).

Also, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by ishitaojha** [comment]
okay thanks , and I'll surely have a look .

**Comment by rt4914** [comment]
Finished in #3250
