### ISSUE TITLE
Radio button flickers when chosen a wrong option 

### ISSUE THREAD

**Issue by pravesh00** [oppia/oppia-android#3263]
**Describe the bug**
The radio button in practise mode flickers or we can say all options refreshes every time we select a wrong option. Also, I think it would be good to have an immediate reflection to the user that the option was correct or wrong by highlighting the selected radio button as green or red for like 500ms to 1000ms.

**To Reproduce**
1. Go to Practise Mode
2. Click on the wrong option of question
3. See the options refreshes every time

**Expected behavior**
Only the wrong radio button selected should reset.

**Screenshots**

https://user-images.githubusercontent.com/64903405/120158301-9aaa0b80-c211-11eb-8c6c-b711e32be680.mp4

**Device**
- Real Device RMX1851
- Android 10 ( SDK-29 )

**Comment by rt4914** [comment]
@pravesh00 That looks like a flicker but thats because on selection of incorrect answer, one item is getting added to the entire list of items.
In your video you can notice that the count in `Previous Responses` increases as soon as you click as the `SelectionInteraction` gets added again at bottom.
