### ISSUE TITLE
Create a BUILD.bazel file in domain/classify and its subdirectories

### ISSUE THREAD

**Issue by fsharpasharp** [oppia/oppia-android#3334]
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## Task

1. Create a BUILD.bazel file in

`domain/src/main/java/org/oppia/android/domain/classify`

and its subdirectories.

1. Define the kt_android_library library/libraries

Based on the imports in the Kotlin files, add the required third_party dependencies to make the libraries build. Check the Useful links section for a list of third_party dependencies.  You may also need to add the non third_party dependencies.

3. Add the directory to the MIGRATED_PROD_FILES of the module's root BUILD.bazel file

4. Add the libraries to the list of deps dependencies in the targets that require the library

You will have to set the apropriate visbility. See the list of visibilities in the link below.

5. Clean up any unused deps dependencies

6. Verify that the app builds

## Useful links

- [BUILD.bazel files](https://github.com/oppia/oppia-android/search?q=filename%3ABUILD.bazel&type=code)
- [Visibilities](https://github.com/oppia/oppia-android/blob/76dc13dba3ad77aecd2218a5372949d6551f12fe/BUILD.bazel)
- [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl)

**Comment by rt4914** [comment]
@deepanshu731 Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by rishidyno** [comment]
@BenHenning I wanted to know what names to give to the following `kt_android_library` in the `BUILD.bazel file`
Because these have pretty big names. you could give me a few examples and I will name others accordingly.

I think that
`DragDropSortInputHasElementXBeforeElementYClassifierProvider.kt` file should be named as `has_element_X_before_element_Y`
  
and those which ends with `RuleClassifierProvider`
should be named as for eg: 
`TextInputContainsRuleClassifierProvider.kt` file should be named as `contains_rule` or `contains_rule_provider`.

and those which ends with `Module`
should be named as for eg:
`TextInputRuleModule` as `text_input_rule_module`.

![image](https://user-images.githubusercontent.com/78549195/145388604-42902f77-ca10-42c9-8159-9775fe6aab27.png)

**Comment by BenHenning** [comment]
@rishidyno I think for those packages it's fine just to have a single library called "classifier_providers" and then a second library for the module. The former should be visibility restricted to only places that need to access the provider whereas the module needs to have module visibility (since they are used broadly).
