### ISSUE TITLE
Merge hints_and_solution_fragment.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3535]
Currently there are 4 versions of `hints_and_solution_fragment.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

**Note**: In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.

**Comment by addy-zero** [comment]
Interested!

**Comment by adizcode** [comment]
@rt4914 I have a small query

The portrait files (for phone and tablet) both have an identical AppBarLayout that wraps the Toolbar, whereas both the landscape files just have a Toolbar.

In order to merge all files into one, I'll need to add the same AppBarLayout to the other two files as well. So should I open another issue for that?
