### ISSUE TITLE
Uninstalling & reinstalling application does not reset administrator PIN 

### ISSUE THREAD

**Issue by rolandbellerud** [oppia/oppia-android#3611]
**Describe the bug**
If you forget your Administrator PIN number, the Oppia instructions are to uninstall the app and then reinstall it to reset it. Due to the data back up on Android, this does not work. When you uninstall the app and then reinstall it, the account is not reset, and you remain unable to log into the Administrator profile. 

**To Reproduce**
1. Set Administrator PIN 
2. Uninstall application
3. Reinstall application
4. Attempt to log in and see that the account/PIN have not been reset. 

**Expected behavior**
Uninstalling and reinstalling the app should reset the data, so you can create a new Administrator PIN and log into the application 

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Device**
- Google Pixel 5
- Alpha release 

**Additional context**

**Comment by BenHenning** [comment]
I think this is caused by https://stackoverflow.com/a/33176898. It's an interesting edge case that comes from us not fully understanding how Android backups work. We either need to disable Android backup support (not ideal since we don't have remote syncing for lesson progress), or provide an alternative flow for resetting the PIN (unclear since we don't have remote profile syncing support). This will require input from product to determine how we should proceed.

**Comment by KolliAnitha** [comment]
On uninstalling and reinstalling the app we see issue #4518. To reset admin PIN now on clicking Forgot PIN, Reset oppia button is seen which deletes data. On reopening the data user can set the pin.
