### ISSUE TITLE
Introduce smoke tests in CI for instrumentation targets

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3618]
Add CI check to check if the targets will build successfully. 

https://github.com/oppia/oppia-android/pull/3505#issuecomment-889677240 For details.

**Comment by FareesHussain** [comment]
@BenHenning I'm wondering what rule to use here.

like you've mentioned https://github.com/oppia/oppia-android/pull/3505#issuecomment-889677240 here that we need something like
```
bazel test //instrumentation:build_instrumentation_targets
```
to check these.

To me it looks like a target that contains all the targets we need to build in the CI for these smoke tests.


but instead can't we just do `bazel build //instrumentation:all` here.
in this case we can also shift the oppia_test to the instrumentation package as in the 2.3 pr we need it to access a separate AndroidManifest.

**Comment by BenHenning** [comment]
> @BenHenning I'm wondering what rule to use here.
> 
> like you've mentioned [#3505 (comment)](https://github.com/oppia/oppia-android/pull/3505#issuecomment-889677240) here that we need something like
> 
> ```
> bazel test //instrumentation:build_instrumentation_targets
> ```
> 
> to check these.
> 
> To me it looks like a target that contains all the targets we need to build in the CI for these smoke tests.
> 
> but instead can't we just do `bazel build //instrumentation:all` here. in this case we can also shift the oppia_test to the instrumentation package as in the 2.3 pr we need it to access a separate AndroidManifest.

Didn't address this originally, but the main reason we can't use 'all' is by introducing a smoke test, we actually turn a build verification check into a test (i.e. one that's picked up by ``bazel test``) which means it will be included in the possible output from ``ComputeAffectedTests``. This is ideal since it ensures verification of these builds happens automatically in the current CI configuration and happens only when necessary (i.e. instrumentation dependencies change).
