### ISSUE TITLE
No back navigation arrow or title in exploration player

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#363]
The exploration player needs to have both a back navigation arrow and an exploration title, per the mocks.

**Comment by BenHenning** [comment]
@rt4914 sending this to you to route since this feels like it could be done as part of #42.

**Comment by rt4914** [comment]
@BenHenning The latest develop has the title in exploration activity.

Regarding, back navigation button on toolbar, the [mocks](https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/40d6cf5f-f673-42c8-af15-035f711ef6b9/PM-IN-Introduction-) does not have that. And that might be because of "Return to Topic Dailog" shown on back press. So should we update the mocks or is it intentional that we do not want to keep back button on toolbar while playing the exploration?

@BenHenning @mschanteltc Need your view points on this.

**Comment by BenHenning** [comment]
Let's keep the arrow out for now, though we may want to revisit adding it for consistency with other activities.
