### ISSUE TITLE
Images are not rendering in multiple choice

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3765]
To repro: play through 'What is a  Fraction?' until the question starting with '"Very good! Now look at these cakes,"'.

The multiple choice bullet list is blank (the images flicker before disappearing when navigating to the state):

![image](https://user-images.githubusercontent.com/12983742/131921906-2e43100d-6ed9-4b11-a48b-03c62d182295.png)

Note that this was encountered on #3764. I haven't verified whether it is encountered on develop, but it's quite likely to be. We should find the root cause (https://github.com/oppia/oppia-android/wiki/Revert-&-regression-policy#how-to-find-the-offending-commit) and then determine what the fix should be, and whether a rollback is beneficial.

**Comment by BenHenning** [comment]
@anandwana001 since this is MR3 blocking, can you PTAL? This is higher priority than fixing KitKat support.

**Comment by BenHenning** [comment]
Odd. After leaving the device open for a while, the images eventually appeared. Maybe a weird internet flake that persisted?

**Comment by anandwana001** [comment]
I will check this out.

**Comment by anandwana001** [comment]
I checked with the latest develop branch, and I am seeing this issue with the single/multiple-choice question. This issue is the same we faced earlier too. 

https://github.com/oppia/oppia-android/issues/3514

For me, What I did is move back to prev state and coming back to the state with these option and image showed up.

![Screenshot_20210906_134239](https://user-images.githubusercontent.com/25057618/132184240-56c09690-351d-4d64-af85-b98cf663cff7.png)
![Screenshot_20210906_133010](https://user-images.githubusercontent.com/25057618/132184261-545fdea6-a2fd-430d-87bc-99213f710de8.png)

**Comment by anandwana001** [comment]
After running app over multiple previous commits, I found a commit which is introducing this issue. 
7505dd5cdd5dac4437722fe23e907d5249810b6d

@rt4914 If you could help here with the fix or should we move to the revert and regression policy as per standard rule?

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).
