### ISSUE TITLE
Story list drop-down arrow touch target is too small

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#383]
Although the drop-down arrow touch target is at least 48dp for the play tab story list tiles, it looks like it should be bigger. Tapping too far above or below unexpectedly opens the story list rather than expanding it in-line. This touch target should probably take up this whole part of the tile until we decide how to address potential usability issues with the dual tap targets on the same tile.

**Comment by rt4914** [comment]
@BenHenning Currently, the develop code works in following ways:

1. Click on StoryName -> Opens "ChapterList in Next Screen" (StoryActivity).
2. Click anywhere on item item except "StoryName", it will expand/contract the card.

Issues in current card:
- The touch target for "StoryName" is less that `48dp` and fails at accessibility test, and if we use `minHeight=48dp`, this will make the UI look bad.
- The "StoryName" `TextView` is `wrap_content` in width.

@BenHenning so based on your issue description, I am not able to get that same expected behaviour in my latest develop code.

**Comment by BenHenning** [comment]
I think you're right--with the recent changes this is better. I identified this with a build from last Thursday, so I suspect we've since fixed this.
