### ISSUE TITLE
[Arabic] Continue button on the left, cards (and lesson) not moving forward 

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3870]
**Describe the bug**
The "continue" button for proceeding to the next card is placed on the left on a certain card in each chapter and is not moving to the next card on click, while being taken to the previous card. 

**To Reproduce**
1. Go to Oppia App with Arabic language selected as the system language 
2. Click on a lesson 
3. Complete a few cards 
4. See error on a certain card 

**Expected behavior**
The "continue" button should be on the right and the lesson should move on to the next card on clicking "continue".

**Demonstration**
![Screenshot_٢٠٢١١٠٠٢-٠٠٤٩٢٠.png](https://user-images.githubusercontent.com/27875087/135708868-12294d4d-846b-445e-b752-f007750e90ef.png)

![Screenshot_٢٠٢١١٠٠٢-٠٠٤٨٢٣.png](https://user-images.githubusercontent.com/27875087/135708873-aa7e5727-b065-4be5-9061-76d5f437a0c3.png)

![Screenshot_٢٠٢١١٠٠٢-٠٠٣٨٠٣.png](https://user-images.githubusercontent.com/27875087/135708878-85b7514b-2f73-4ba5-ad45-134dcbcfa11c.png)

**Environment**
- Device/emulator being used: <device version/emulator> Pixel 5
- Android or SDK version (e.g. Android 5 or SDK 21): <os/sdk version> Android 12 
- App version (you can get this through system app settings or via the admin controls menu in-app): <app version>  version 0.6-alpha-7ff1b2bbd2

**Additional context**

**Comment by srushtirk** [comment]
Additional context: 

An additional arrow button is seen on the left side (sometimes both on right and left side), along with the "continue" button. This issue is seen and is consistent only when the arrow button is clicked instead of continue. 

Adding a video for further reference: https://drive.google.com/file/d/12qFBO_1VVximc5mTcxhEaEsMzMsUzfh9/view?usp=sharing

**Comment by BenHenning** [comment]
So upon reviewing the video, I think this is WAI. From talking to Srusthi, we found out that the app above was in Urdu rather than Arabic (hence the RTL), and the English translations (due to having no Urdu translations) led to some UX confusion about navigation directionality. RTL always means that lesson progression is "leftward" (so right arrows go backwards in lesson history) which is exactly WAI since it's the reversed flow when playing through lessons with a left-to-right language.

Closing this as WAI. Thanks for the additional details & discussions @srushtirk.
