### ISSUE TITLE
[A11Y] Rich-text hyperlink text improvement

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3895]
Rich-text hyperlink text improvement is required as per below mentioned error.

<img src="https://user-images.githubusercontent.com/9396084/136244457-9266bfa9-9f1c-425f-879f-5a57fc326214.png" width="250" />

**Comment by rishidyno** [comment]
@Sarthak2601 @anandwana001 @BenHenning Can you please explain this issue in detail. According to my understanding, we have to generate a text in place of `Learn more` which is more descriptive for a particular Lesson/Topic.

**Comment by Sarthak2601** [comment]
> @Sarthak2601 @anandwana001 @BenHenning Can you please explain this issue in detail. According to my understanding, we have to generate a text in place of `Learn more` which is more descriptive for a particular Lesson/Topic.

Yes, sounds about right.

**Comment by BenHenning** [comment]
@rishidyno since the backend doesn't provide additional context for these links, we'll probably need to use text like "Open concept card" to provide context.

**Comment by rishidyno** [comment]
reference layout - `revision_card_fragment`

**Comment by rishidyno** [comment]
@BenHenning  I have created the PR #4078. I have changed the name as suggested, PTAL.

**Comment by BenHenning** [comment]
@rishidyno I don't think #4078 quite solves the problem since that's only affecting a single concept card. In this case, we actually want to default the content description for the link for all concept cards.

**Comment by rishidyno** [comment]
@BenHenning I went through all the concept cards and there are only 2 cards with Rich-text hyperlink. And others have some explanation or sample, or they are empty, and they don't have any rich-text in them. These rich texts are coming from JSON files and which are separate for each concept card. So I think we have to add custom rich text for each of the concept cards.

**Comment by rishidyno** [comment]
Below are the 2 rich text 
I have applied changes for one of them.
| SS1  | SS2 |
| ------------- | ------------- |
| ![Screenshot_20220105_134354](https://user-images.githubusercontent.com/78549195/148183327-b8eca14f-5685-4d45-87f4-67cfb48d3ae2.png)  | ![Screenshot_20220105_134428](https://user-images.githubusercontent.com/78549195/148184153-b564c66c-7fc5-465d-878d-a67d508c8505.png)|

**Comment by BenHenning** [comment]
@rishidyno those are just test concept cards. We actually download a whole different set of lessons for the production version of the app that we upload to the Play Store. If I recall, it has 50+ concept cards that are included with the app.

That's actually why the solution needs to be generalizable since we don't have the option of changing the concept cards or the HTML itself. This is something that the app needs to augment the existing HTML/tags to ensure the description is correct.

**Comment by rishidyno** [comment]
> 

@rt4914  has mentioned that he will discuss this with you personally.

**Comment by BenHenning** [comment]
After chatting to @rt4914, it doesn't seem worthwhile to fix this in the generic case since the link behavior will be essentially the same as for sighted users (and from a technical feasibility perspective, this is hard since Android doesn't provide a way to define a content description for an actual span).

That being said, it's worthwhile to fix the test content to silence this issue. We should turn 'Learn more' into an actual sentence to see if that provides the context that the scanner is looking for.

**Comment by rishidyno** [comment]
@BenHenning @rt4914 What sentence should we use in place of `Learn more`.

**Comment by BenHenning** [comment]
@rishidyno any sentence should work here. Even just: "This concept card demonstrates overall concept card functionality." would be sufficient if it eliminates the accessibility error (you'll need to check this with the accessibility scanner).

**Comment by rishidyno** [comment]
Got it @BenHenning. Thanks!

**Comment by rishidyno** [comment]
Unassigning myself as this needs more discussion.

**Comment by rt4914** [comment]
@rishidyno What more discussion does this need? If I remember correctly, the solution was to update the content to something meaningful so that the error is disabled. Is there something that I am missing ?

**Comment by rishidyno** [comment]
@rt4914  I don't actually remember much about what we discussed earlier but you mentioned that that you will discuss it with Ben and will take another round of look on it.

**Comment by rt4914** [comment]
@rt4914 No worries. I will check and get back to you about this.

**Comment by BenHenning** [comment]
I believe all that's needed here is an update to the revision card's "Learn more" link to add additional context so that the scanner doesn't think it's too short. I think I explained this & provided an example in earlier comments--was there another issue that prevented proceeding with this @rishidyno?

Also, we should re-run the accessibility scanner before and after the fix to verify that:
1. It's still happening
2. That a longer sentence for the link does, indeed, fix the warning

**Comment by rt4914** [comment]
@rishidyno PTAL, Thanks.

**Comment by rishidyno** [comment]
@rt4914 ack. Thanks.

**Comment by rt4914** [comment]
@rishidyno Any updates?
