### ISSUE TITLE
[A11Y] Incorrect string output for `DragAndDrop` answer

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3897]
Incorrect string output for `DragAndDrop` answer as shown below. Instead of this it should be `Incorrect submitted answer`

<img src="https://user-images.githubusercontent.com/9396084/136244818-21ce7a97-72d6-4068-bc85-e83bc3a1ff15.png" width="250" />

**Comment by shakivhussain** [comment]
I would like to work on this bug, please assign me.

**Comment by rt4914** [comment]
@shakivhussain Thanks for showing interest. Please, checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.
Also, once above steps are done please pick issues from [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22).

**Comment by shakivhussain** [comment]
All done @rt4914  sir , Please assign me.

**Comment by shakivhussain** [comment]
I would like to work on this , please assign me.

**Comment by BenHenning** [comment]
Hi @shakivhussain. It looks like #3565 has already been assigned to you. I suggest working to finish that up, first, before taking on another item.

**Comment by vrajdesai78** [comment]
I am working on this issue. I have found that we get the wrong output due to a problem in contentDescription of submitted_answer_item.xml file in which isCorrectAnswer is not returning the proper boolean value but I am not getting how isCorrectAnswer value is changed because every time it's returning true and it's values is not changing.

**Comment by BenHenning** [comment]
@vrajdesai78 once a submitted_answer_item is created for a specific SubmittedAnswerViewModel, it won't ever change (conceptually this is because a submitted answer can't be retroactively changed by the user). However, there is a gap in time where isCorrectAnswer defaults to false before being set to potentially true (see https://github.com/oppia/oppia-android/blob/5801df02317cc3f052d79a3dea8b3becd06bc60d/app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt#L550). You'll need to investigate whether isCorrectAnswer is actually being set to the correct value, and whether that value is being used to set the correct content description. If it isn't being set correctly, you'll need to figure out why.

**Comment by rt4914** [comment]
@Rohit1173 Any updates on this?

**Comment by vrajdesai78** [comment]
I think this issue is now solved in the latest update.

https://user-images.githubusercontent.com/43074241/173336068-52fac59a-2a78-40a9-9a84-c1aedc7a8ad2.mp4

**Comment by BenHenning** [comment]
It's possible this was fixed with the math expressions project since a few issues with the answer handling were addressed. @rt4914 does it look correct now to you per @vrajdesai78's video?

**Comment by rt4914** [comment]
@BenHenning @vrajdesai78 I have checked it on my device too with latest develop and it has been solved. Also the "Please Continue" related accessibility issue has also been solved. 

Closing this issue now.
