### ISSUE TITLE
[A11Y] Onboarding flow improvement

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3899]
Onboarding flow experience can be improved. Current experience is shown below.

https://user-images.githubusercontent.com/9396084/136245319-7bf6397d-697c-4ed7-a11f-8ddf3a15f6be.mp4

**Comment by bkaur-bkj** [comment]
@rt4914 would like to discuss and work on this issue

**Comment by rt4914** [comment]
Reference from @viktoriias : https://developer.android.com/reference/android/view/accessibility/AccessibilityEventSource

**Comment by BenHenning** [comment]
@rt4914 can you clarify what the specific issues are & any recommendations that you may have for what a better solution might look like? Neither were clear to me from the main issue comment.

**Comment by bkaur-bkj** [comment]
@BenHenning sir Upto what I understood and discussed with @rt4914 sir, the issue is that when we are on screen 1 of onboarding and move to screen 2 through next button the focus still lies on next button itself for the second page of onboarding and it does not read any content shown on the screen(fragment), thus it makes difficult for a user to know the screen content as the screen just reads "next button" when moved to next screen. to read whats on screen then user needs to make swipes to take focus to fragment from the bottom navigation bar

**Comment by BenHenning** [comment]
Thanks @bkaur-bkj. Continuing the discussion on the PR to keep it one place.

**Comment by rt4914** [comment]
Closing this issue because of following points.

**Challenge**
We normally use `announceForAccessibility` to announce anything on command but in this case that's not possible because we want to announce the content inside `ViewPager` after the `Next` button has been clicked which is outside the `ViewPager`. ViewPager does not support `announceForAccessibility` and because of that its not a straight-forward solution.

**Possible Solution**
It can work if we had all 4 screens as fragments inside a viewpager and the `Next/Skip/Dots` were part of fragment too. But that means the even the designs will change along with minor changes in functionality.

**Summary**
Considering that the possible solution can bring in a lot of change and currently its not a bad experience for accessibility users too therefore closing this for now.
