### ISSUE TITLE
 Implement edit profile screen inside a fragment

### ISSUE THREAD

**Issue by yash10019coder** [oppia/oppia-android#4028]
issue #3241 

refer to this issue for the details and impletation for this issue
this issue basically resolves the hi-fi profile in administrator controls.

 Implementing edit profile screen inside a fragment

**Comment by BenHenning** [comment]
@yash10019coder this seems to be missing some details. Can you please add code links to anything that you think should change, and be a bit clearer on what you expect the outcome to be? I'm not actually positive what exactly needs to be done to resolve this.

Also, assigning this to you given that you're implementing #4029. Note that I'm not looking at that PR to understand this issue since it's generally good practice for issues to be sufficiently self-documenting to stand on their own without the PR for them already existing (consider that many issues are addressed by people other than the person who created them, so capturing the context needed to resolve the issue clearly is really important).
