### ISSUE TITLE
Implement success criteria metrics for lesson checkpointing

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4042]
**Is your feature request related to a problem? Please describe.**
Lesson checkpointing was implemented as a GSoC project last summer, but we didn't have time to implement the success criteria metrics expected for the feature [here](https://docs.google.com/document/d/1d8yjwz76mngtsPRxC7fubgLKg8mfA7kG1sWRWdbiaVw/edit#bookmark=id.2zyjd5vygmcv).

**Describe the solution you'd like**
The metrics should be implemented using the existing analytics framework. This feature should be documented at least in this issue with a high-level overview with the changes that need to be done in the code before actually starting implementation. A design document is not needed.

**Describe alternatives you've considered**
N/A

**Additional context**
None

**Comment by BenHenning** [comment]
@rishidyno this is actually a higher priority feature than #3825 and isn't blocked on UX (though it isn't a new UI). Might you be interested working on in this issue?

**Comment by theMr17** [comment]
## Implementation

The metrics will be logged using the existing analytics framework. Each of the following events will be logged alongwith the _ExplorationContext_. As discussed with @adhiamboperes, here are the places where each of the event logs shall be triggered.

1) **Progress saving success count**
This count will include the number of instances successful in saving user’s progress. The event will be triggered in _ExplorationProgressController_, the point where we receive a response that the checkpoint was successfully saved. [Here.](https://github.com/oppia/oppia-android/blob/3ced7e14a8bff8c3757ed15a1626b0e63c6ce14d/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt#L949)

2) **Progress saving failure count**
This count will include the number of instances failed in saving user’s progress. The event will be triggered in _ExplorationProgressController_, the point where we receive a response that the checkpoint has failed to save. [Here.](https://github.com/oppia/oppia-android/blob/3ced7e14a8bff8c3757ed15a1626b0e63c6ce14d/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt#L951)

3) **Lessons saved advertently count**
This count will include the number of instances user exits the exploration advertently, i.e., by using the 'X' icon or the back button. The event will be triggered in _ExplorationActivityPresenter_, inside _backButtonPressed_ function. [Here.](https://github.com/oppia/oppia-android/blob/3ced7e14a8bff8c3757ed15a1626b0e63c6ce14d/app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt#L326)

4) **Lessons saved inadvertently count**
It will be preferred to calculate the metric as shown below, because logging the event will be a bit complex in this situation. This metric includes scenarios of app crashes, updates, topic deletions and reinstalls, so separating them from total saving attempts will be difficult.

    _Lessons saved inadvertently count = Total saving attempts count - Lessons saved advertently count_

5) **Total saving attempt count**

    _Total saving attempt count = Progress saving success count + Progress saving failure count_

6) **Start over count**
Already implemented as a part of Learner Analytics. [Here.](https://github.com/oppia/oppia-android/blob/3ced7e14a8bff8c3757ed15a1626b0e63c6ce14d/domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/LearnerAnalyticsLogger.kt#L232)

7) **Continuation count**
Already implemented as a part of Learner Analytics. [Here.](https://github.com/oppia/oppia-android/blob/3ced7e14a8bff8c3757ed15a1626b0e63c6ce14d/domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/LearnerAnalyticsLogger.kt#L225)

8) **Correct answer count after returning to the lesson**
A new variable will be introduced in _ExplorationProgressController.ControllerState_ to log the event only when a resumed lesson is played. The event will be triggered in _ExplorationProgressController_, inside _ControllerState.submitAnswerImpl_ function. [Here.](https://github.com/oppia/oppia-android/blob/3ced7e14a8bff8c3757ed15a1626b0e63c6ce14d/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt#L636)


9) **Incorrect answer count after returning to the lesson**
This count will be same as above but will be logged in case of incorrect answer submission.

## File Changes

The following tables list the files that will be modified in each of the modules.

### App module
|File|Change|
|--|--|
|[ExplorationActivityPresenter.kt](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt)|Log lessons saved advertently.|

### Domain module
|File|Change|
|--|--|
|[ExplorationProgressController.kt](https://github.com/oppia/oppia-android/blob/develop/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt)|Log progress save success & failure, correct & incorrect answer.|
|[LearnerAnalyticsLogger.kt](https://github.com/oppia/oppia-android/blob/develop/domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/LearnerAnalyticsLogger.kt)|Log the events via _AnalyticsController_.|

### Model module
|File|Change|
|--|--|
|[oppia_logger.proto](https://github.com/oppia/oppia-android/blob/develop/model/src/main/proto/oppia_logger.proto)|Introduce context fields for above events.|

### Utility module
|File|Change|
|--|--|
|[EventBundleCreator.kt](https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/android/util/logging/EventBundleCreator.kt)|Convert new fields to _ActivityContext_.|
|[StandardEventTypeToHumanReadableNameConverterImpl.kt](https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/android/util/logging/StandardEventTypeToHumanReadableNameConverterImpl.kt)|Add human readable names for above events.|
|[KenyaAlphaEventTypeToHumanReadableNameConverterImpl.kt](https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/android/util/logging/KenyaAlphaEventTypeToHumanReadableNameConverterImpl.kt)|Add human readable names for above events.|
