### ISSUE TITLE
Remove info tab and add info icon 

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4085]
**Is your feature request related to a problem? Please describe.**
Per feedback received from multiple user studies, learners do not find it useful to have the info tab as a separate tab (as well as the first tab that they come across)

**Describe the solution you'd like**
Remove the Info tab and add an info icon to the screen as below:
![Screen Shot 2022-01-07 at 3 35 15 PM](https://user-images.githubusercontent.com/27875087/148620431-abc8da18-1e7c-4a28-82ec-f52256b1fd6c.png)

**Describe alternatives you've considered**
Alternatives considered in this doc: https://docs.google.com/a/google.com/document/d/1oD8LTH71BBsXxn5R1F8To3EsV786w0q-EQFcb4hRiik/edit

**Additional context**

**Comment by srushtirk** [comment]
cc @mschanteltc

**Comment by BenHenning** [comment]
I'm curious about this. Won't moving the info to a toolbar button all but guarantee that people won't see it?

There are currently two ways to navigate to to a topic: the topic list, and recent activity. Opening a topic from the topic list navigates the user to the info tab, whereas recent activity navigates them to the lessons tab. Have we considered also navigating the user to the lessons tab when opening from the topic list (maybe only when they've started the topic)? Hiding the info tab might have the opposite desired effect: people may not be aware of what a topic is.

That being said, this might work better once we have topic downloads since they will be able to review the info tab prior to downloading, and after that having the info hidden away but still accessible could work. If that's the desired outcome, maybe we should bundle this with the topic downloads work rather than framing it as a separate beta MR1 item since we probably wouldn't want it completed before downloads.

**Comment by srushtirk** [comment]
@BenHenning Agree! 

I have two suggestions here if we are keeping the current workflow: 1) Default to lessons tab once the user opens a topic (this was one of the considerations during our discussion last year) 2) Hide the topic downloads button until downloads are available. 

We can close this issue and I will follow up with Shin who I believe is working on topic downloads.

**Comment by BenHenning** [comment]
@srushtirk in that case, closing this issue until we have a finalized product strategy.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by BenHenning** [comment]
This will be completed as part of @JishnuGoyal's onboarding fixes project.

**Comment by adhiamboperes** [comment]
This has been fixed. We redesigned the Topic page so that we have only lessons and revision tabs by default.

**Comment by BenHenning** [comment]
Also to add to this: we have no plans to add an info icon now. It's more likely that the current topic info content will be presented on a future "download topic" landing page.
