### ISSUE TITLE
Ban inappropriate words in profile names 

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4087]
**Is your feature request related to a problem? Please describe.**
Ban offensive and swear words under user profile names so that kids (learners) do not add inappropriate profile names to their accounts. 

**Describe the solution you'd like**
Here is a list of words that should be banned from profile names in the app. 
https://docs.google.com/spreadsheets/d/1aXBkwOoelPfqbIroiPVEeU3Mjt2AcinUKgh-UBzA3xs/edit#gid=0

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by BenHenning** [comment]
@srushtirk would this list also need to be internationalized? It's also generally pretty easy to circumvent simple censors (and doing something more elaborate can get very complex). I don't think we have any similar filtering on Oppia web, though we do have moderators & admins that could take action if people did this. Given the nature of solving this problem properly, I'm wondering how much this matters/whether we actually see it being a problem.

**Comment by srushtirk** [comment]
Hi @BenHenning, this list definitely needs to be internationalized, and therefore I want to suggest if we can have an ongoing list that we can update timely to add inappropriate words to be banned in the app from other languages?

Since the devices may be shared between multiple users (kids) of different ages (between 5-14 yrs), and in scenarios of unsupervised learning, this issue could potentially raise a concern between teachers or parents. To build the trust on Oppia's end around this, I believe this is an important problem to solve (but not a P0).

Let me know if this makes sense. 

I'd also like to know @isalooo @seanlip 's thoughts.

**Comment by seanlip** [comment]
I'll defer to @isalooo (Android product lead) on this.

**Comment by BenHenning** [comment]
@srushtirk perhaps we should discuss this in the next product sync--it'd be nice to get broader thoughts on this.

**Comment by BenHenning** [comment]
So I think, for now, we're inclined not to proceed with this work. It's not entirely obvious to me that it's solving any known problems (particularly since profiles are only local to a user's device at the moment). We're also expecting devices to be primarily managed by a teacher, parent, or older sibling, and our new onboarding flow is orienting the profile creation process to generally be done by that individual rather than the learner directly.

We've also not seen many issues on the Oppia web side with public usernames. I'm inclined to close this until we have a clearer need to address to help reduce the number of overall issues that we're tracking in the project.

Thanks again for filing this @srushtirk!
