### ISSUE TITLE
Remove colors_migrating.xml post dark mode implementation.

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4147]
Currently `colors_migrating.xml` contains color declarations which are supposed to be in color_defs.xml but have not yet been renamed yet to have actual color name instead of names linked to their use and components. This is a temporary measure to make sure other 4 color files follows the convention decided for them.

`colors_migrating.xml` should be removed once dark mode is implemented to most screens via `color_defs.xml`.

Reference : #4032

**Comment by MohitGupta121** [comment]
@rt4914 or @BenHenning Can I take this issue or wait till all dark mode complete ?

**Comment by MohitGupta121** [comment]
@BenHenning Some `colors_migrating.xml` directly using in `.kt` or `Test` files not anywhere in `xmls`. So for those colors can we use them directly from `color_def.xml` ? For eg. For this file https://github.com/oppia/oppia-android/blob/7def64a0c997aa7e9418bb22c9ed5ba04e617f3a/app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt#L33

These all `avatar_background_colors` only using in `.kt`. 

For Tests and .kt files we need to add Regex Check or we only add regex check for `.xmls` as per this issue https://github.com/oppia/oppia-android/issues/4396 ?

**Comment by MohitGupta121** [comment]
@BenHenning can you please have a look on this comment https://github.com/oppia/oppia-android/issues/4147#issuecomment-1422778464

**Comment by MohitGupta121** [comment]
@BenHenning Actually my main problem is in `colors_migrating.xml`, some colors are used in .kt files such as [`ProfileChooserFragmentPresenter.kt`](https://github.com/oppia/oppia-android/blob/7def64a0c997aa7e9418bb22c9ed5ba04e617f3a/app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt#L33). These include [`avatar_background_colors`](https://github.com/oppia/oppia-android/blob/7def64a0c997aa7e9418bb22c9ed5ba04e617f3a/app/src/main/res/values/colors_migrating.xml#L67), XYZ (see link) and ABC (see link). These colors aren't used in any other XML files. Can we change the .kt files to reference colors from color_def.xml instead of component_colors.xml if we using [Regex ](https://github.com/oppia/oppia-android/issues/4396) only for .xml files?

**Comment by MohitGupta121** [comment]
@BenHenning Actually my main problem is in `colors_migrating.xml`, some colors are used in .kt files  such as [`ProfileChooserFragmentPresenter.kt`](https://github.com/oppia/oppia-android/blob/7def64a0c997aa7e9418bb22c9ed5ba04e617f3a/app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt#L33). These include [`avatar_background_colors`](https://github.com/oppia/oppia-android/blob/7def64a0c997aa7e9418bb22c9ed5ba04e617f3a/app/src/main/res/values/colors_migrating.xml#L67). These colors aren't used in any other XML files. Can we change the .kt files to reference colors from color_def.xml instead of component_colors.xml if we using [Regex ](https://github.com/oppia/oppia-android/issues/4396) only for .xml files?

**Comment by MohitGupta121** [comment]
@BenHenning @rt4914 I got some help from Sean, and now I am planning to use [`avatar_background_colors`](https://github.com/oppia/oppia-android/blob/7def64a0c997aa7e9418bb22c9ed5ba04e617f3a/app/src/main/res/values/colors_migrating.xml#L67) directly from `color_defs` only in [`ProfileChooserFragmentPresenter.kt`](https://github.com/oppia/oppia-android/blob/7def64a0c997aa7e9418bb22c9ed5ba04e617f3a/app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt#L33) because `avatar_background_colors` getting in random basis in ProfileChooserFragment (whose background is already dark in color for both light/dark mode, so it's not effecting the user)  as this only avatar_background_colors blocking me to make PR. But now get unblocked by Sean.

But @BenHenning if you have any other suggestions then please share.
Thanks.
