### ISSUE TITLE
Add dark mode support to HomeActivity, DrawerFragment, RevisionCardActivity, ConceptCardFragment and AudioFragment

### ISSUE THREAD

**Issue by ayush0402** [oppia/oppia-android#4194]
Add dark mode support to HomeActivity, DrawerFragment, RevisionCardActivity, ConceptCardFragment and AudioFragment

Go through this [wiki](https://github.com/oppia/oppia-android/wiki/Dark-Mode) to get started.

**Comment by atharvashirdhankar** [comment]
Can I work on this issue?

**Comment by ayush0402** [comment]
@StarTrooper08 Assigned.

**Comment by Akshatkamboj14** [comment]
Hey, @bhaktideshmukh actually in today's meeting sean and I were confused about this PR actually, I think we both were working on it and we were supposed to split the 5 parts in this PR into 3 and 2, am I Right?
and if you are working on this PR, please let me know. and if not then also, so that we can write in the description of this PR and also make it clear on the clam team.

**Comment by bhaktideshmukh** [comment]
> Hey, @bhaktideshmukh actually in today's meeting sean and I were confused about this PR actually, I think we both were working on it and we were supposed to split the 5 parts in this PR into 3 and 2, am I Right? and if you are working on this PR, please let me know. and if not then also, so that we can write in the description of this PR and also make it clear on the clam team.

I'll cover the other two parts -- HomeActivity and RevisionCardActivity

**Comment by Akshatkamboj14** [comment]
Thanks @bhaktideshmukh.
