### ISSUE TITLE
"Copy" function misaligned in the UI

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4281]
**Describe the bug**
Copy function next to the device ID is misaligned in the UI

**To Reproduce**
1. Go to Administrator Controls 
2. Click on Profile Learner IDs & Sync Status
3. See error next to Device ID

**Expected behavior**
"Copy" icon and text should be horizontally aligned after the Device ID. This possibly means reducing the font for "Device ID"

**Demonstration**
<img width="343" alt="image" src="https://user-images.githubusercontent.com/27875087/161140570-031b4966-f8af-4bab-8885-6561b9a1d8a5.png">

**Environment**
- Device/emulator being used: Pixel 5
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.7-alpha-d1b2827517

**Additional context**

**Comment by yash37158** [comment]
can I work on this issue?

**Comment by yash37158** [comment]
I can't see profile learners' id and sync status options in administrative control, can you please guide me through this issue? @srushtirk

**Comment by yash37158** [comment]
![administrative-controls](https://user-images.githubusercontent.com/68152307/161375766-9159062e-3367-42ba-b5e3-b181cd350cda.jpg)

**Comment by BenHenning** [comment]
Apologies @yash37158 this issue corresponds to UI functionality that's not yet checked in. Assigning to myself to avoid further confusion.

**Comment by BenHenning** [comment]
This problem is fairly easy to reproduce by maximizing device zoom. It actually gets exacerbated by:
- Very long profile names (completely cuts off the copy button)
- Display + font zoom (which completely cuts off the installation ID copy button)

Note that the above was tested on a Nexus 5X which has a smaller screen to start with, so that exact behavior may not be observed on larger screen densities.

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).
