### ISSUE TITLE
Automatically Update Topics options doesn't do anything in Administrator Controls

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4315]
**Describe the bug**
Automatically Update Topics options doesn't do anything in Administrator Controls

**To Reproduce**
1. Go to 'Administrator Controls'
2. Click on 'Automatically Update Topics'

**Expected behavior**
On turning on this control whenever there is an update to a topic it should be auto updated
![Screenshot 2022-04-25 8 21 23 AM](https://user-images.githubusercontent.com/101634267/165012817-4d7bf6ff-24e5-4ca5-988e-e95077650271.png)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment]
The solution for this is to introduce a new platform parameter (see [this wiki page](https://github.com/oppia/oppia-android/wiki/Platform-Parameters-&-Feature-Flags)) and hide the 'download permissions' section entirely (similar to what's being done in #4204 minus the extra testing work since that PR is fixing a few general issues with how we change platform parameters in tests).

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by KolliAnitha** [comment]
Download permissions section is no loger available in beta build 0.10-beta-5e64fae55e
![Screenshot_20221114-092351](https://user-images.githubusercontent.com/101634267/201593364-f08e2aea-bf75-4961-8dc1-cafc12496a31.jpg)
