### ISSUE TITLE
Unable to complete chapter 'What is Division'

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4329]
**Describe the bug**
Unable to complete chapter 'What is Division'

**To Reproduce**
1. Go to 'All Topics'
2. Click on 'Division'
3. Select Chapter 1 'What is Division'
4. Click on Continue until you get to the cookies question 
5. Enter 6/2 as answer and submit

**Expected behavior**
On giving 6/2 as answer it should display correct and continue button should be enabled

Actual behavior:
On entering 6/2 as answer, 'No, that's not correct' is displayed and unable to proceed further

![Screenshot_2022-04-28-10-35-49-81_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/165680309-75064ec7-6491-4411-9460-37699424613c.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

Note: Working fine in web
![Screenshot 2022-04-28 10 34 48 AM](https://user-images.githubusercontent.com/101634267/165680170-78942561-a8db-4dd2-84bc-7815e36a457e.png)

**Comment by BenHenning** [comment]
This requires more investigation and may indicate a serious issue with the math expressions implementation. Going to take this to dig into it.

**Comment by BenHenning** [comment]
I've been able to debug this. I believe it's coming from the fact that rule inputs on Oppia might fail some of the new validation checks (such as redundant parentheses). In particular, the answer above is checking against ``(6)/(2)`` which fails the optional parentheses validation error. I'll remove the extra validation for web-provided values, though this is an interesting edge case since web rule input should, in the future, follow the same validations as user answers (/cc @seanlip for visibility).

**Comment by seanlip** [comment]
Noted -- thanks @BenHenning. Copying @iamprayush too for info.

**Comment by KolliAnitha** [comment]
Verified in 0.7-alpha-6c08d882d3. Completed the chapter by submitting the answer as 6/2

**Comment by BenHenning** [comment]
For searching context, this issue was found in 0.7-alpha (MR4).
