### ISSUE TITLE
Lessons not displaying fully in portrait mode.

### ISSUE THREAD

**Issue by latifatakin** [oppia/oppia-android#4350]
Student unable to view some parts of the screen content until the student rotated the phone into Landscape mode.
![Screenshot_20220402-203631~2](https://user-images.githubusercontent.com/102434385/167181285-2cdc5b24-990a-4eba-ac6a-f441c4ca7200.png)
![Screenshot_20220403-051145~2](https://user-images.githubusercontent.com/102434385/167181307-e5b2cf33-2745-4a90-b59b-3513750eb880.png)

The information about the device used are;
Device name: TECNO SPARK 4
Model: TECNO KC8
Android version:10
HiOSv6.2.0

**Comment by BenHenning** [comment]
Hi @latifatakin.

Thanks for filing this issue! Fortunately, we're aware of this (see #4027) and have recently fixed it. The fix will be available in the next alpha release of the app (which should be available on Play Store sometime next week).

Closing this in the meantime as we already have an issue to track it, and it's been closed due to being fixed.

**Comment by latifatakin** [comment]
Hello Ben,

The User studies was conducted with the alpha version of the Oppia app. I
was granted early access because I am an Outreachy applicant contributing
to Oppia.

**Comment by BenHenning** [comment]
@latifatakin there were 2 versions of the alpha app (confusingly) shared with Outreachy applicants. Do you know which version of the app this issue corresponds to? If it's 0.6, then it's likely fixed. If it's 0.7, this is a new issue that we should reopen and investigate.
