### ISSUE TITLE
On trying to change admin password, it is asking to uninstall and reinstall the app. Even after doing it unable to change the pin

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4366]
**Describe the bug**
On trying to change admin password, it is asking to uninstall and reinstall the app

**To Reproduce**
1. Go to 'Profile selection page'
2. Click on 'Admin'
3. In the Enter PIN dialog box click on I forgot my pin link
4. Uninstall and Install the app
5. The PIN is not changed 

**Expected behavior**
Admin should be able to change the PIN

https://user-images.githubusercontent.com/101634267/169010373-deec27ef-004f-4aab-bee9-850340fa2ce8.mp4

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

**Comment by BenHenning** [comment]
This is a known issue that comes from two separate problems working in concert: (1) no remote profiles (which makes resetting reliably difficult), and (2) automatic app backups via the Android system making the reinstall flow not actually fix the problem.

You can work around the issue by going into app system settings and clearing data (which also forces the app to reset). This is, unfortunately, a very severe way of fixing the problem as it wipes all progress and profiles on the device. If that's not acceptable in your particular case (i.e. for testing), let me know and we can try a more direct route to fix it.

The above workaround is definitely not user-friendly, and it's far too punishing to the user since their progress isn't remotely synced. We have a project in the works to find a better medium-term solution until actual remote profiles are added. I'm not sure if there's a tracking issue for this yet, so it's nice to have this issue to track it.

Edit: Also, this is likely a hard blocker for the beta release since it's likely for users to hit this, and it more or less breaks the app for them in a way that they are unlikely to be able to figure out a workaround for on their own.
