### ISSUE TITLE
Add placeholders for text based interactions

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4446]
**Is your feature request related to a problem? Please describe.**
In the app interactions where the user is expected to type an input as an answer, some users do not understand that they are supposed to type inside the white text box. 

**Describe the solution you'd like**
Add appropriate placeholder text or hints. These placeholders should be similar to the ones shown on the oppia website.

**Comment by seanlip** [comment]
Noting that this needs to be done for Alpha MR5, for at least TextInput and NumericExpressionInput. It is vital for making the lessons understandable and playable.

**Comment by BenHenning** [comment]
I've investigated this further and verified that:
- All text-based interactions except text input correctly fall back to a built-in placeholder even if the creator overrides the interaction's placeholder with an empty string
- All text-based interactions have placeholder support except numeric input which uses an always-present hint text
- The importer hasn't changed since April, and the latest export data seems correct for the placeholder definition
- The state in question (within Parts of Multiplication Expressions) which was missing a text placeholder does seem to correctly have that placeholder text when viewed locally
- The code that computes the hint text for text input was introduced as part of the internationalization project 11+ months ago and hasn't changed
- The hint text disappears as part of Android's TextView if the keyboard is opened and then collapsed, and stays gone unless the user navigates to an earlier card and back

I suspect that the last point is resembling the actual underlying problem here, and it's not obvious how to solve this reliably (since it probably requires altering focus based on whether the keyboard is up, and this is a well-known problem area in Android that can be challenging & unreliable to work with).

Per a discussion with Sean, we're deprioritizing this for the immediate Alpha MR5 release as well as Beta MR1. More product consideration is needed here, and we should consider potential UX approaches that might help mitigate the user confusion without needing to approach this unreliably on the technical side.

**Comment by BenHenning** [comment]
Also to clarify one thing: I am going to go ahead and add a default text input placeholder to bring it into conformance with the other text input interactions (just so that the user never sees an empty box except in the keyboard scenario). This is a departure from web behavior, but it's a simple change that seems reasonable.

**Comment by BenHenning** [comment]
Correcting one thing from above: per chatting with Sean, we do want to try and get the multi-line hint working since that at least helps mitigate a big part of the problem (as the hint text includes vital information per Sean's earlier comment).

**Comment by JishnuGoyal** [comment]
Thanks for confirming this Ben! I have added the latest code to my PR to handle folding of lines the way we want for our current implementation. Please let me know what are your thoughts! @BenHenning
