### ISSUE TITLE
TextView & Toolbar color changes in Topic screen

### ISSUE THREAD

**Issue by MihirShirgaonkar** [oppia/oppia-android#4461]
****TextView & Toolbar color changes in Topic screen in Info , Lesson and Practice fragments when switched from light mode to dark mode****

To Reproduce

Open the app
Click on any lesson
Keep dark mode on

![3](https://user-images.githubusercontent.com/62711294/180615018-9cfb2396-4dea-411f-80e4-873392dc4ca9.jpeg)     ![4](https://user-images.githubusercontent.com/62711294/180615019-20969dc9-d5ba-407d-83b4-a11c9762eaca.jpeg)

![5](https://user-images.githubusercontent.com/62711294/180615066-0f4befab-1f6f-44e2-884c-3d75b57021ce.jpeg)     ![6](https://user-images.githubusercontent.com/62711294/180615068-d3b969e3-af10-4148-8d3c-37da18b5c286.jpeg)

![1](https://user-images.githubusercontent.com/62711294/180615096-4a7cb486-2a53-4fcf-a1b2-9a8169426db1.jpeg)     ![2](https://user-images.githubusercontent.com/62711294/180615097-25815c0e-0470-41f7-aa21-c2a2af22384a.jpeg)

**Environment Tested**
- Device/emulator being used: Samsung M12
- Android or SDK version :  Android 11 
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Comment by BenHenning** [comment]
Thanks @MihirShirgaonkar.

I'm assuming that this is because the topic activity hasn't yet been migrated to support dark mode, but the toolbar and some headings have. Can you confirm @ayush0402 @rt4914?

**Comment by MohitGupta121** [comment]
@MihirShirgaonkar @BenHenning This issue is now fixed in latest build.
So can we close this issue?



|||
|:----------------------------------------:|:-----------------------------------------:|
| ![](https://user-images.githubusercontent.com/76530270/204598446-6bff5812-2723-4929-9429-21cb37d0cd94.png) | ![](https://user-images.githubusercontent.com/76530270/204598455-7115f4a6-319c-4154-882d-ea5c3ac11d7c.png) |
|||

**Comment by BenHenning** [comment]
Hmm the toolbar and tab colors seem different in dark mode @MohitGupta121. Shouldn't that be addressed before closing this?

**Comment by MohitGupta121** [comment]
@BenHenning is actually in the develop, it's already according to the mockup.

https://xd.adobe.com/view/c05e9343-60f6-4c11-84ac-c756b75b940f-950d/screen/1adacef0-f245-4115-a0e0-d1c2e7d5a0bb/

Actually, this issue is open in July but I implement dark mode for the topic fragment on September #4177 

Also, I test it on my emulator and it's working fine for me:-
https://user-images.githubusercontent.com/76530270/204702110-dccdb177-3289-45ba-b2cb-77b513a017e9.gif

That's why there is no need for this issue.

And only Lesson Fragment Dark Mode is pending and its is already opens in #4624
