### ISSUE TITLE
Unwanted character observed in Revision card- Representing Unknowns with variables

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4531]
**Describe the bug**
Unwanted character observed in Revision card- Representing Unknowns with variables

**To Reproduce**
1. Go to 'Expressions and Equations' - Revision card
2. Click on 'Representing Unknowns with variables'
3. Scroll down to 'Representing unknowns with variables' section
4. See the line ' The problem is, we don't know what number it is - yet.'

**Expected behavior**
-- is not needed in the sentence 

**Demonstration**
![Screenshot_2022-08-25-10-12-21-49_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/186576715-a6bd68de-7243-4b9a-94c7-f47378b2b62b.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by seanlip** [comment]
Thanks @KolliAnitha! The "--" was meant to convey "...", but I can see how it's confusing, and I've removed it.

This is now fixed on the web server and should be fixed in the Android app on the next content pull. We already have other issues open that depend on the next content pull (and therefore "track" it), so I will close this.
