### ISSUE TITLE
Submit button is not enabled after inputting the answer

### ISSUE THREAD

**Issue by Ryggs** [oppia/oppia-android#4539]
**Describe the bug**
The Submit button highlight is not enabled after user inputs answer instead throws exception..

Exception: 
```
2022-08-09 21:13:49.707 21191-21191/org.oppia.android E/StateFragment: Failed to retrieve answer outcome
    java.lang.IllegalStateException: Expected interaction TextInput to have classifier for rule type: CaseSensitiveEquals, but only has: [Contains, Equals, FuzzyEquals, StartsWith]
        at org.oppia.android.domain.classify.AnswerClassificationController.classifyAnswer(AnswerClassificationController.kt:62)
        at org.oppia.android.domain.classify.AnswerClassificationController.classify(AnswerClassificationController.kt:39)
        at org.oppia.android.domain.exploration.ExplorationProgressController$submitAnswerImpl$2.invokeSuspend(ExplorationProgressController.kt:573)
        at org.oppia.android.domain.exploration.ExplorationProgressController$submitAnswerImpl$2.invoke(Unknown Source:10)
        at org.oppia.android.domain.exploration.ExplorationProgressController.tryOperation(ExplorationProgressController.kt:731)
        at org.oppia.android.domain.exploration.ExplorationProgressController.tryOperation$default(ExplorationProgressController.kt:727)
        at org.oppia.android.domain.exploration.ExplorationProgressController.submitAnswerImpl(ExplorationProgressController.kt:554)
        at org.oppia.android.domain.exploration.ExplorationProgressController$createControllerCommandActor$1.invokeSuspend(ExplorationProgressController.kt:435)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
``` 

**To Reproduce**
1. Go to 'Topic Ratios and Proportions - Lessons Tab'
2. Click on 'Expand Ratios: Part 1.'
3. Scroll down to 'exercises in “Order is important”'

https://user-images.githubusercontent.com/31986629/187138908-cb654cb4-d163-4c79-b0f3-1c0fcffc1524.mp4

**Expected behavior**
The submit button should be enabled after the correct answer, is entered.

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

**Environment**
- Device/emulator being used: **TECHNO POP 2F**
- Android or SDK version (e.g. Android 5 or SDK 21): **Android 10**
- App version (you can get this through system app settings or via the admin controls menu in-app): <app version 1.0>

**Additional context**

**Comment by BenHenning** [comment]
This is being caused by old test data that hasn't been migrated with the latest structure changes from Oppia web (the app was updated to no longer use CaseSensitiveEquals, but the test data wasn't). This will only affect developers, and the fix requires updating the test explorations to migrate CaseSensitiveEquals per https://github.com/oppia/oppia/blob/bb0ecf6867242b6d40a57feb4ca74c79f94e86c1/core/domain/question_domain.py#L795.

**Comment by aayushimathur6** [comment]
@BenHenning I m trying this issue and it's really new for me, and finding it a bit difficult just to solve. I have understood the issue but can you please explain where do I learn more to get it solved? So can you please send me similar PR links for that as this is my first good second issue

**Comment by BenHenning** [comment]
> @BenHenning I m trying this issue and it's really new for me, and finding it a bit difficult just to solve. I have understood the issue but can you please explain where do I learn more to get it solved? So can you please send me similar PR links for that as this is my first good second issue

@aayushimathur6 the first place to start is to make sure that you can consistently reproduce the issue. Have you done that?

Once done, you can use log statements and breakpoint/step debugging to trace what's happening leading up to the failure. The best place to start looking code-wise is wherever is "closest" to the observed failure (which may be a UI, or perhaps a message that's included in an error stack trace). You can then work backwards based on the observed call hierarchy. This will help you build an understanding of what's going on, and when.

Once you have a sense of how this part of the app is working, you can analyze it in a case where it behaves correctly and compare that to the case where it fails. This can help you isolate what's specifically going wrong. That observation plus the context will provide you with a complete understanding of the problem.

From there, you need to analyze the code to determine why the problem is happening, and figure out what needs to be changed to stop it (note: not silence, but actually fix the behavioral problem that's causing the failure).

This is a bit of a generic response, but I suggest following it as your main debugging flow. If you get stuck at any part, please share your findings up to that point and what you're specifically stuck on.

**Comment by Ryggs** [comment]
Hi @BenHenning what is the progress on this? Asking this for reference

**Comment by BenHenning** [comment]
@Ryggs I believe this is actively being worked on, but @aayushimathur6 can you confirm?

**Comment by aayushimathur6** [comment]
@Ryggs @BenHenning  Actually I am working on it, this issue is new to me so currently I am learning about the things and can do this by the 20th of this month

**Comment by BenHenning** [comment]
Thanks for the update @aayushimathur6!

**Comment by debz-g** [comment]
Hello @BenHenning is this issue being actively worked upon. Asking for reference.

**Comment by aayushimathur6** [comment]
yes @debz-g, I am working on it

**Comment by aayushimathur6** [comment]
> Hello @BenHenning is this issue being actively worked upon. Asking for reference.

@debz-g Yes, I am currently working on it.

**Comment by debz-g** [comment]
> > Hello @BenHenning is this issue being actively worked upon. Asking for reference.
> 
> @debz-g Yes, I am currently working on it.

Ok that's great. I'll look for some other issue to solve.

**Comment by aayushimathur6** [comment]
Hey @BenHenning, While I was reproducing the issue again I didn't come across any bug in the submit button as it was enabled after inputting the correct answer but when I rewatched the video carefully I observed that there is an issue in the video given here, actually the spelling of mango was wrong "it was written mangoe". I think this might be the issue and that's why the submit button is not working.

**Comment by seanlip** [comment]
@aayushimathur6 But even if the spelling is wrong, the app shouldn't be throwing an error, right? It should still be handling that case properly.

**Comment by aayushimathur6** [comment]
@seanlip I totally agree, I will look after the errors

**Comment by BenHenning** [comment]
@masclot PTAL.

**Comment by masclot** [comment]
I did all the exercises in the 'Topic Ratios and Proportions' lesson. I didn't experience any problem and the answers are not case sensitive. Also, no stacktraces in logcat. Maybe this bug has already been fixed?

I can't find the text "CaseSensitiveEquals" in oppia android code; however, it is used in some asset files. For example: [2mzzFVDLuAj8.textproto](https://github.com/oppia/oppia-android/blob/d74576dae6ec2e6a8d14226ae47ab2f87ef6c881/domain/src/main/assets/2mzzFVDLuAj8.textproto#L3014) 

Is that fine?

**Comment by adhiamboperes** [comment]
Hey @masclot , 
From the prrevious comments I can see that:
1. You can reproduce this issue if you input a wrong answer for the affected state.
2. This is a dev-specific issue, so the is in the developer assets. We don't have support for the CaseSensitiveEquals, but it is in the assets so we need to remove it from the assets. I think from a prior discussion, we had identified making changes to the `test_exp_id.2json` as the one that need to be fixed. Please verify and revert.

**Comment by masclot** [comment]
Thanks @adhiamboperes I could reproduce the issue now.

**Comment by masclot** [comment]
Regarding the file test_exp_id_2.json, that file is correct and does not contain CaseSensitiveEquals.
Now, as I mentioned earlier, there are other files that contain the word CaseSensitiveEquals. Updating those to Equals fixes the issue in my workspace. However, those files have a weird name, which could mean they are generated and we would need to also fix the generator. Do you now if that is the case?
The list of files is:
- 2mzzFVDLuAj8.json
- 2mzzFVDLuAj8.textproto
- 5NWuolNcwH6e.json
- 5NWuolNcwH6e.textproto

**Comment by adhiamboperes** [comment]
> Regarding the file test_exp_id_2.json, that file is correct and does not contain CaseSensitiveEquals. Now, as I mentioned earlier, there are other files that contain the word CaseSensitiveEquals. Updating those to Equals fixes the issue in my workspace. However, those files have a weird name, which could mean they are generated and we would need to also fix the generator. Do you now if that is the case? The list of files is:
> 
> * 2mzzFVDLuAj8.json
> * 2mzzFVDLuAj8.textproto
> * 5NWuolNcwH6e.json
> * 5NWuolNcwH6e.textproto

These files are developer only and bundled with the repo so it's okay to edit them. Asset generation broadly is changing, but not right away.

I think you should edit the json files.

**Comment by BenHenning** [comment]
So both the JSON and textproto assets will need to be changed. JSON ones can be verified with the Gradle build, and textproto needs to be verified with the Bazel version of the app along with changing the following value to true (temporarily for local testing purposes):

https://github.com/oppia/oppia-android/blob/5e74b842d565ace32bd6f839f4b835037cd3cd36/utility/src/main/java/org/oppia/android/util/caching/CachingModule.kt#L22
