### ISSUE TITLE
Improve text scaling according to accessibility scanner 

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4586]
**Describe the bug**
In Android 12, accessibility scanner is showing suggestion to improve text scaling for cases in which we have set fixed width or height of view group which will create a problem in scaling test. 

**Expected behavior**
Accessibility scanner should not show any improvements for text scaling

**Demonstration**
![image](https://user-images.githubusercontent.com/43074241/189544669-f4b6120c-82a6-4309-a035-55580c970a84.png)

![image](https://user-images.githubusercontent.com/43074241/189544672-0e478efc-31b1-49c1-9fd6-21f1eb5e621c.png)

**Environment**
- Device/emulator being used: Realme GT Master Edition
- Android version: Android 12
- App version : 1.0.0

**Comment by BenHenning** [comment]
Reopening due to #4587 being reverted in #4686.

**Comment by vrajdesai78** [comment]
@BenHenning @rt4914 for this particular issue only in promotes story card we are getting text scaling issues, other than that almost all of the issues are already solved in this #4686 PR. 

For promoted story card I get following suggestion from accessibility scanner. 
![image](https://user-images.githubusercontent.com/43074241/199917710-4ac01d5a-eb23-40d4-8d35-c19e43f1362a.png)

The suggestion shows that **ViewGroup has a fixed width and contains a TextView with scalable text**. Here, to solve this issue we need to set width as wrap content. As per the #4684 we can't set the width as wrap content, we need to give fixed width such that all promoted story cards have same width. 

I think that here we need to compromise with the text scaling issue as we can't fix it for promoted story card.

**Comment by rt4914** [comment]
@BenHenning @vrajdesai78 I have tried solving this issue and so far using `sp` instead of `dp` for fixed width is the only solution that looks best to me. Have a look at below screenshots (smallest text vs largest text)

<img src="https://user-images.githubusercontent.com/9396084/200055938-bd95f207-fa23-42b5-9f59-6844653c8f06.png" width="250" /> <img src="https://user-images.githubusercontent.com/9396084/200055962-00b1c767-6c53-43cc-a886-f9fe6c9fbd8f.png" width="250" />

<img src="https://user-images.githubusercontent.com/9396084/200055981-70561ad4-a720-4b0c-a96d-4fc264696559.png" width="400" /> <img src="https://user-images.githubusercontent.com/9396084/200055987-a3e7f6b5-131d-4298-989d-77ab2d99b583.png" width="400" />


Other solution attempts were:
- removing fixed width altogether - results in distorted cards
- using autotextview - works only above version 26

**Comment by vrajdesai78** [comment]
@rt4914 I agree with your solution, but if we make the fontsize in dp then accessibility scanner will give another suggestion that fontsize should in sp instead of dp. So any approach we take, we have to compromise to atleast one problem either accessibility or inconsistent size of card. I think we can't keep the size of card inconsistent and also doing dp will give another suggestion of changing it back to sp. So, I think that even if we go with the current implementation it's fine. @BenHenning WDYT

**Comment by rt4914** [comment]
> instead

Just to be clear I have not used dp for font size. Instead I have used sp for the card width. Also, notice that the width/height of card is different in above screenshots that's because of using sp, if it was dp then it would have been fixed width/height.
