### ISSUE TITLE
Fragment returns null view on config change in submit time error

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4708]
**Describe the bug**
Whenever we compute submit time error, rotates screen and again submits answer [without error] the app crashes and in log it shows that fragment is returning null view. 

**To Reproduce**
1. Go to 'MathInputInteraction'
2. Submit answer with error
3. Rotate screen
4. Remove '?' from fragment.view? in hideKeyboard method in StateFragmentPresenter.kt 
5. Submit answer without error.
6. Observe error log 

**Expected behavior**
App should not return null view, it should return a non-null view when we submits answer without error. 

**Screen Recording**

https://user-images.githubusercontent.com/43074241/201446130-19fcfa6f-48e8-408d-844b-0416065e142e.mp4

**Environment**
- Device/emulator being used: Realme GT Master Edition
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Comment by BenHenning** [comment]
This can also be seen by playing up to fractions in the test prototype exploration and introducing a submit-time error (e.g. by typing "1/" and tapping 'Submit'), then rotating the screen.

**Comment by mukulasija** [comment]
i would like to work on this issue

**Comment by adhiamboperes** [comment]
> i would like to work on this issue

Could you please give a brief overview of your proposed solution?

**Comment by EmmanuelDav** [comment]
> Could you please give a brief overview of your proposed solution?

is this issue still available,  if so to answer the question i would consider, I would consider using ViewModel to store and manage the data associated with the Fragment. ViewModel survives configuration changes and it can help maintain the state of the view making it not to return a null view. 

Alternatively, I could use setRetainInstance(true) to retain the configuration changes after screen rotation. I haven't viewed the source code, I don't know  which would work

**Comment by Bontrey** [comment]
Since there's some interest here and I've also been looking at this, thought that I should share my current findings:

The current problem reproduced by the initial description (causing an input error, then rotating) seems to be that the recycler view becomes empty.

This happens because the answer is [submitted](https://github.com/oppia/oppia-android/blob/c3bb6013df78f75f038117cbf9c361cbe9f7ba74/app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt#L205) even if it's an [empty default answer](https://github.com/oppia/oppia-android/blob/c3bb6013df78f75f038117cbf9c361cbe9f7ba74/app/src/main/java/org/oppia/android/app/player/state/StateViewModel.kt#L109).

The submit runs into an [error](https://github.com/oppia/oppia-android/assets/698755/0c862225-609e-4c4a-aa0f-b3f35f87fc29), and this [tryOperation](https://github.com/oppia/oppia-android/blob/c3bb6013df78f75f038117cbf9c361cbe9f7ba74/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt#L604) ends up in the [catch block](https://github.com/oppia/oppia-android/blob/c3bb6013df78f75f038117cbf9c361cbe9f7ba74/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt#L799), which does not run recomputeCurrentStateAndNotifySync to emit a new EphemeralState. The last emitted state result was `Pending` from `SUBMITTING_ANSWER`, so the itemList is never [repopulated](https://github.com/oppia/oppia-android/blob/c3bb6013df78f75f038117cbf9c361cbe9f7ba74/app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt#L327) (`Pending` result does not cause `processEphemeralState` to run) after it's cleared out from the Fragment recreation on configuration change.

I think the solution might just be to return null instead of a default answer and to not attempt the submit in that case, but the testing instructions are outdated (and I'm new to real world android development) so I'm having trouble adding a unit test. Maybe I'll ask in the discussions.

EDIT: asked at #5184

**Comment by adhiamboperes** [comment]
@EmmanuelDav setRetainedInstance can be risky, because it can lead to memory leaks. I think [these answers](https://stackoverflow.com/questions/21203948/setretaininstancetrue-in-oncreate-fragment-in-android) offer a pretty good explanation.

**Comment by adhiamboperes** [comment]
@Bontrey, Could you share a draft PR with your fix?

**Comment by Bontrey** [comment]
https://github.com/Bontrey/oppia-android/commit/1560426425a8168320cb817e745dc3c36456bb1b

But satisfying "Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing" will take some time for StateFragmentTest since there are many tests and some of them seem to fail for unrelated reasons ([example](https://github.com/oppia/oppia-android/assets/698755/1e44c395-045e-4138-b753-9c0c823372f2)).

I'll keep going on it though

**Comment by adhiamboperes** [comment]
> [Bontrey@1560426](https://github.com/Bontrey/oppia-android/commit/1560426425a8168320cb817e745dc3c36456bb1b)
> 
> But satisfying "Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing" will take some time for StateFragmentTest since there are many tests and some of them seem to fail for unrelated reasons ([example](https://github.com/oppia/oppia-android/assets/698755/1e44c395-045e-4138-b753-9c0c823372f2)).
> 
> I'll keep going on it though

Can you push the code so that the tests run on our CI?
