### ISSUE TITLE
Navigation directionality is wrong in RTL layouts in state fragment

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#474]
See:

![image](https://user-images.githubusercontent.com/12983742/69600412-62df5980-0fc5-11ea-8974-d5679df051b0.png)

Waiting on clarification from @mschanteltc on what the correct behavior should be.

**Comment by FareesHussain** [comment]
For reference: Testing RTL using psuedolocale

<img src="https://user-images.githubusercontent.com/54740946/103888139-36739780-510a-11eb-980c-b94398e7b3e5.png" width="32%"/>

**Comment by mschanteltc** [comment]
The text in the blue container and the heading "What is a Fraction?" should be right-aligned.

**Comment by FareesHussain** [comment]
I guess this is blocked on localization support.

**Comment by rt4914** [comment]
@veena14cs PTAL at this and close/fix as needed.

**Comment by veena14cs** [comment]
@rt4914 this should be fixed in localization support. RTL is working fine. Added screenshot for reference. 
Also the Navigation icon is fixed #3373 .


![Screenshot_1626858008](https://user-images.githubusercontent.com/16301028/126462077-e4ecf656-e7fb-4284-b6e7-20488d6c47ab.png)


![Screenshot_1626858311](https://user-images.githubusercontent.com/16301028/126462590-ee52134f-9cd1-4695-868f-b5808685bb0a.png)

**Comment by rt4914** [comment]
@veena14cs Makes sense. Shifting this to the Localisation project.

**Comment by BenHenning** [comment]
Confirming that this works as expected per when I tested RTL support.
