### ISSUE TITLE
[BUG] : On changing the system language to Arabic, the content in the existing profiles is not translated 

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#5053]
**Describe the bug**
On changing the system language to Arabic, the content in the existing profiles is not translated

**To Reproduce**
1. Go to Settings- Update system settings to Arabic
2. Open Oppia - Admin 
3. See that the content is not translated to Arabic
4. Now go back and create a new profile 
5. Login to that profile and see that the content in it is translated to Arabic

**Expected behavior**
Exisiting profiles content also should be translated to Arabic

**Demonstration**

https://github.com/oppia/oppia-android/assets/101634267/9cf9b12f-df02-4407-b496-f37fa22c29d4

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.11-beta-8e0fcf19ac

**Comment by seanlip** [comment]
@KolliAnitha Does this happen on out-of-the-box installation (i.e. Oppia is installed for the first time on a phone that already has Arabic as its system language), or only for cases where the system language was non-Arabic when Oppia was installed and then changed to Arabic?

**Comment by KolliAnitha** [comment]
@seanlip, this happened when the system language was English, installed Oppia then logged in as Admin opened a lesson in a Topic and then changed system language to Arabic, restarted the device. Logged in to Oppia as Admin(Profile selection page is in Arabic), the content i.e Home all the topic tiles, lessons are not translated. But on creating a new profile the content, topic tiles, lessons is seen in Arabic.

**Comment by adhiamboperes** [comment]
Hi @KolliAnitha, this is the expected  behaviour of the new app language feature. We now have app language and profile language:
1. The app language will default to the locale of the language when the app is installed. Any profile created in this locale, e.g admin, and any manually created profile at the time, will default to use the app language. 

- If a user does not make any changes, we keep the system language
- If a user changes the language on their profile using the language selector screen, we will change the content and app strings that they view - topic tiles, lessons, only on their profile.
- When they navigate back to the profile chooser page, they will see the profiles in the app language == system language.

2. If you switch system language, any new profiles created will be in the app/system language by default.

- If you then switch the language of that profile using the language selector feature, the changes are constrained to that profile only.
- The profile chooser screen retains system language

3. The overall result is that each profile can use their preferred language on the same device.

In your case the admin profile remained in english because that's the default profile language.

**Comment by adhiamboperes** [comment]
Closing this since the issue described is the expected app behavior. See https://github.com/oppia/oppia-android/issues/5053#issuecomment-1589380479

**Comment by Ai80-8** [comment]
Delete it all
