### ISSUE TITLE
[Feature Request]: Remove all-caps for all buttons and change to sentence case

### ISSUE THREAD

**Issue by jlevick** [oppia/oppia-android#5135]
### Is your feature request related to a problem? Please describe.

We are currently using all-caps for buttons (ex: CONTINUE, CANCEL) and the UX writing team has decided to move forward with changing to sentence case (ex: Continue, Cancel, Ok, Submit, Close, Skip).

### Describe the solution you'd like

Changing all-caps buttons to sentence case, thank you!

**Comment by ShubhadeepKarmakar** [comment]
May I work on this issue?

**Comment by jlevick** [comment]
Hi @seanlip, I might be in over my head here :) for context, Adhiambo recommended I file a feature request, and our comments about this are here:

https://www.figma.com/file/2dohUd2hHPAvhehWWygw7k/%E2%9C%8F%EF%B8%8F-Jiwon-Choi---Oppia-drafts?type=design&node-id=1123-5949&mode=design&t=huoYlkpVldG2q8mg-0

I've never filed a feature request and wasn't sure what information needed to be included. I'm not sure if we need to get design and/or product involved, but essentially the UXW team is hoping to change all-cap buttons to sentence case for the entire Android app (also the entire website, but I don't feel I should be requesting changes there as I'm only on the Android team.) I'm unsure of where a list of buttons is to include for the dev team. 

I wanted to loop you in for guidance before I dig myself in deeper! Thank you.

**Comment by seanlip** [comment]
Hi @jlevick, I think this is a straightforward change that is fine to apply app-wide, but there's an order of operations I would suggest:
- Confirm with the Android design leads (@kaiyuxu and @jiwonc26) that this is fine. Feel free to cc me as PM.
- Work with the Android design leads to ensure the design style guide for Android (see guides [here](https://github.com/oppia/design-team)) is updated to only use sentence case, and to mandate sentence case in future designs.
- Only after this is done: file the issue here asking the dev team to change things. (What you have filed above is fine, just specify that it should be done for all buttons in the app.)

UXW is welcome to propose something similar for Web as well, but the process above should be followed so that everyone is on the same page. They can contact the Web design leads at design@oppia.org.

I'll close this issue for now but please feel free to re-file it once the steps above are completed. Thanks!
