### ISSUE TITLE
MissingDefaultResource + AppCompatCustomView + FragmentTagUsage

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5186]
## Description 
 We would like to fix all the remaining lint issues on Oppia Android in the "MissingDefaultResource + AppCompatCustomView + FragmentTagUsage" category.

## Steps To Reproduce
Run the following command from a terminal in a checked-out Oppia Android repo:

`./gradlew :app:lint`

**Output:** 

- MissingDefaultResource mainly has a single issue with a string which has different names in english and other translations. It can be easily fixed, by matching the name of that string in english and other translations.
- For AppCompatCustomView, it can be fixed by replacing the Normal views with AppCompat views
- <fragment/> tags can be replaced with <androidx.fragment.app.FragmentContainerView/>.

## Expected Behavior
Running the command above should not show any errors.

**Comment by sichchurov** [comment]
./gradlew :app:lint
This command is always finished with failed

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 6m 38s
155 actionable tasks: 11 executed, 144 up-to-date

@adhiamboperes I have resolved the FragmentTagUsage issue
**here is a lint report screenshot before**
[![Fragment-Tag-Usage-before.png](https://i.postimg.cc/1tfx77Mf/Fragment-Tag-Usage-before.png)](https://postimg.cc/JDVdGqfL)

**and after**
[![Fragment-Tag-Usage-after.png](https://i.postimg.cc/d0ZmW8rJ/Fragment-Tag-Usage-after.png)](https://postimg.cc/nsZDr93W)

**Comment by theMr17** [comment]
Hi @sichchurov, Please look into those issues which are not assigned to anyone.

**Comment by BenHenning** [comment]
#5191 was reverted, so this is no longer fixed.

**Comment by M-e-h-u-l-21** [comment]
@BenHenning ./gradlew :app:lint , this command always resulted in errors.
I've fixed the AppCompatCustomView and FragmentTagUsage issues.
This is the lint report after fixing the mentioned issues:
![image](https://github.com/oppia/oppia-android/assets/96437826/cbd4477f-522f-4959-9703-80beedda7067)

**Comment by theMr17** [comment]
Unassigning myself, as this can be a good first issue for new contributors.

**Comment by tobioyelekan** [comment]
Hi @adhiamboperes new contributor here, can I pick this up?

**Comment by adhiamboperes** [comment]
> Hi @adhiamboperes new contributor here, can I pick this up?


Hi, what's your proposed solution for this issue? Please refer to the issue thread for previously proposed solutions, and note that we had to revert a PR solving this due to some crashes.

**Comment by tobioyelekan** [comment]
Hi @adhiamboperes
- For AppCompatCustomView -> I replaced it with AppCompat Views
- For FragmentTagUsage, I followed a similar approach to the previous solution, but I used `onViewCreated` to setup the drawer, which is guaranteed to be called after the binding is initialized in `onCreateView()`.

    **More details:**
    I also placed a breakpoint to ensure the desired order:
    `onAttach()`->`setupDrawer()`->`onCreateView()`->`onViewCreated()`


![Screenshot 2024-11-19 at 1 25 07 AM](https://github.com/user-attachments/assets/69e27dae-8c47-41c8-ae56-1ede2ae3f620)

This solution worked, but I noticed an issue when I minimized and returned to the app, the drawer stopped working, which I believe is because when `handleOnRestart()` is called, it re-initializes the drawer fragment and calls `setUpDrawer()` again. At this point, I believe the fragment is not recreated thereby not calling `onCreate()` and `onViewCreated()`, I believe this should be set once, and will be called again when the activity is destroyed. I temporarily removed the `handleOnRestart()` and everything seems to be working fine.

Please let me know what you think, I look forward to your response @adhiamboperes

**Comment by adhiamboperes** [comment]
@tobioyelekan, please feel free to create a PR for this. At the same time, does removing the`handleOnRestart()` call remove any required re-initializations? Please ensure that the app works the same way before and after the fix.

**Comment by tobioyelekan** [comment]
@adhiamboperes so far, there's no additional re-initializations, PR ready for review https://github.com/oppia/oppia-android/pull/5582
