### ISSUE TITLE
[Feature Request]: Remove the EnableContinueButtonAnimation Feature Flag

### ISSUE THREAD

**Issue by kkmurerwa** [oppia/oppia-android#5226]
### Is your feature request related to a problem? Please describe.

Since the EnableContinueButtonAnimation has been officially rolled out, the related feature flag can now be removed.

### Describe the solution you'd like

I would like to have the EnableContinueButtonAnimation feature flag removed from the FeatureFlagConstants file since the feature it was gating has officially been released and is stable. Any of its related constants and dagger module declarations should also be removed. Lastly, I would like the if statements surrounding any functionality that is gated using this feature flag to be removed as well.

**Comment by deonwaju** [comment]
Hello, Is there anyone on this? I would like to take this up.

**Comment by kkmurerwa** [comment]
Hi @DeonWaju. @adhiamboperes should first triage this issue since I have just created it before it can be assigned. It also requires modifications on code that hasn't been merged yet and it is currently undoable until PR #5203 is merged.

**Comment by deonwaju** [comment]
Ok thanks, any other first issues I can take up pending the time? @kkmurerwa

**Comment by kkmurerwa** [comment]
@adhiamboperes will recommend a few first issues you can look at as she's triaging this issue. In the meantime, you can also go to [this link](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee) to check out some of the first issues that haven't been assigned to someone yet.

**Comment by deonwaju** [comment]
Thanks

**Comment by kmanikanta335** [comment]
can i work on this issue ?

**Comment by adhiamboperes** [comment]
@DeonWaju can you please give an overview of how you plan to solve the issue, including the files that need to be changed.

**Comment by adhiamboperes** [comment]
> can i work on this issue ?

If you'd like to work on an issue please make sure you describe your proposed solution on the issue and we will then assign it to you.

**Comment by deonwaju** [comment]
Hello, @adhiamboperes 

Here is my proposed solution and files to be changed

1. Go to PlatformParameterConstants.kt file and remove from line 173 to 182 and remove unused imports.

<img width="884" alt="Screenshot 2023-11-15 at 12 21 43" src="https://github.com/oppia/oppia-android/assets/54560535/9a3a7b61-68d0-4ca2-9780-44487ab2528e">

2. Go to ContinueButtonView.kt  file, remove from line 28 and 29 the declaration of the lateinit var enableContinueButtonAnimation: PlatformParameterValue<Boolean> and the field injection
and remove unused imports

<img width="738" alt="Screenshot 2023-11-15 at 12 06 02" src="https://github.com/oppia/oppia-android/assets/54560535/12072b8f-b64e-431e-8e55-539d380f0f69">

3. In the same ContinueButtonView.kt  file, remove the "if statement" logic on line 122 and the enclosing brackets.

<img width="888" alt="Screenshot 2023-11-15 at 12 24 19" src="https://github.com/oppia/oppia-android/assets/54560535/8be81b25-9577-4519-bff1-4a06cd0051fb">

4. Finally, Go to the following files belowand remove occurences of @provide and @EnableContinueButtonAnimation and the provide function instances in all the module declarations. Also remove the unused imports from each file
TestParamenterModule.kt, PlatformParameterModule.kt, PlatformParameterAlphaModule.kt, 
PlatformParameterAlphaKenyaModule.kt 
Example of lines to look out for and remove from the above files are in the screenshot below

<img width="851" alt="Screenshot 2023-11-15 at 12 35 34" src="https://github.com/oppia/oppia-android/assets/54560535/ef7d97c5-0b82-4385-9f4b-356879f048d0">

5. (A) Remove declaration of TestPlatformParameterModule.forceEnableContinueButtonAnimation() from all test functions namely:
testContinueInteractionAnim_openPrototypeExp_checkContinueButtonAnimatesAfter45Seconds(), testConIntAnim_openProtExp_orientLandscapeAfter30Sec_checkAnimHasNotStarted(), testConIntAnim_openProtExp_orientLandAfter30Sec_checkAnimStartsIn15SecAfterOrientChange(), testContNavBtnAnim_openMathExp_checkContNavBtnAnimatesAfter45Seconds(), testContNavBtnAnim_openMathExp_playThroughSecondState_checkContBtnDoesNotAnimateAfter45Sec(), testConIntAnim_openFractions_expId1_checkButtonDoesNotAnimate()
in StateFragmentLocalTest.kt file

(B) Remove function declaration TestPlatformParameterModule.forceEnableContinueButtonAnimation(false) from setup() function
in StateFragmentTest.kt
 
(C) Remove function declaration TestPlatformParameterModule.forceEnableContinueButtonAnimation(false) from setup() function
in ExploreActivityTest.kt

Please look through if the proposed solution meet the project requirements, so that I can make a PR. Thanks
Kind regards.
@adhiamboperes updated

**Comment by adhiamboperes** [comment]
Thanks @DeonWaju, I have assigned the issue to you.
