### ISSUE TITLE
[BUG]: Code coverage workflow assumes a PR must be present

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#5486]
### Describe the bug

https://github.com/oppia/oppia-android/actions/runs/10375275721/job/28732138722 from the latest develop run:

```
Run peter-evans/create-or-update-comment@v4
Error: Missing either 'issue-number' or 'comment-id'.
```

### Steps To Reproduce

Submit a PR and observe CI when coverage finishes.

### Expected Behavior

CI should pass on develop with coverage running.

### Additional Context

It seems this is tied to trying to upload the report comment--that step should only be run if there's an actual PR to comment to.

**Comment by BenHenning** [comment]
@Rd4dev please consider this a blocker for finishing your project (and incorporate a fix in your latest PR if you can).

**Comment by Rd4dev** [comment]
@BenHenning, sure. Thanks for filing the issue. And recently with #5483 a permission issue occurred with code coverage workflows' upload comments job when it was triggered by forks. Still working on it. Should that too be filed as a new Issue?

**Comment by Rd4dev** [comment]
Also, regarding this issue I think this issue occurred since `check_coverage_results` was not set with requirement to wait for `publish_coverage_report`, 

```
  check_coverage_results:
    name: Check Code Coverage Results
    needs: [ compute_changed_files, code_coverage_run, evaluate-code-coverage-reports ]
```

so, when merged the `check_coverage_results` it immediately closed the pr while `publish_coverage_report` was still running and trying to get the pr-number even after pr being closed. If that's the case I guess fix should be straightforward by just adding the needs for `check_coverage_results` to include the `publish_coverage_report`. 

But is there any way to actually test if that's working, would closing the pr in between work?

**Comment by BenHenning** [comment]
We should make sure the comment upload works for forks, too. Is that not possible?

For verifying it, you'll probably need to use your fork since we won't know if it works on develop until the PR is merged.
