### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#560]
This is a part of documentation needed to bring new contributors onboard.
Mainly this should align with https://github.com/oppia/oppia/blob/develop/.github/README.md file.

**Comment by anandwana001** [comment]
Starting from bottom few sections like Support, License and Keeping in touch will remain the same as https://github.com/oppia/oppia/blob/develop/.github/README.md.

- In place of Installation, we can put Android App Development Set up where we can provide Android Studio downloadable link. 
- List of libraries we are using in our codebase
- Few Screenshots
- Link of our testing wiki page and Architecture as well as working on UI wiki page
- Guidance on submitting a PR -> Necessary steps like Sign the CLA, Fill in the Oppia contributor survey and Oppia Android coding style guide should be placed directly in README rather than giving a link. This makes the contributor more involved in contributing

Once I get completed with my current assigned issue, could I take this on up?

**Comment by BenHenning** [comment]
We should also include some brief overview of what the project itself is. I think it's fine for you to work on @anandwana001 but I think we should focus on other priorities at the moment (specifically items in the Alpha milestone).
