### ISSUE TITLE
Admin Pin in Add profile

### ISSUE THREAD

**Issue by chrk2205** [oppia/oppia-android#756]
In the first activity, while  creating a new user application asks for ADMINISTRATOR PIN 
if the Pin goes wrong the box turns RED. It looks better if the box become empty as in the Admin Account login

can i work on this??
![WhatsApp Image 2020-03-08 at 00 03 38](https://user-images.githubusercontent.com/44704035/76150541-c3585980-60d1-11ea-847d-3fe73ca07b73.jpeg)
.

**Comment by rt4914** [comment]
@chrk2205 Actually, this implementation is correct, because we should not remove/add anything which user is not expecting, if we remove the content, user will be disturbed because that is not something that user has done. 

Thanks for you suggestion, but in this case current implementation is more4 user friendly. You can close this PR. Thanks.
