### ISSUE TITLE
In HDPI device shadow looks odd for edit profile image thumbnail.

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [oppia/oppia-android#980]
In HDPI device shadow looks odd for edit profile image thumbnail in profile progress activity.
Tested on Nexus S.
<img width="199" alt="Screenshot 2020-04-14 at 11 55 27 AM" src="https://user-images.githubusercontent.com/9396084/79192734-e69bc480-7e46-11ea-858d-144f0a64a9cf.png">
https://github.com/oppia/oppia-android/pull/998#discussion_r411155467

**Comment by BenHenning** [comment]
Given lower priority, moving to beta.

**Comment by rt4914** [comment]
Closing this issue because of two points:

1. The shadow of profile-picture does look correct in latest develop.
2. The shadow of edit-icon needs to be updated in https://github.com/oppia/oppia-android/issues/4104 too and therefore I have merged both the issues so that they can be tested/solved together.

Check screenshots in issue description of https://github.com/oppia/oppia-android/issues/4104
